export type ApiErrorCode =
  | 'ACCESS_REQUESTS_DISABLED'
  | 'ACCESS_REQUESTS_UNAVAILABLE'
  | 'ACCESS_REQUEST_CONFLICT'
  | 'ACCOUNT_STATE_CONFLICT'
  | 'ASSESSMENT_NOT_READY'
  | 'AI_CORRECTION_NOT_ELIGIBLE'
  | 'AI_CORRECTION_CRITERION_UNKNOWN'
  | 'AI_CORRECTION_UNAVAILABLE'
  | 'INSUFFICIENT_CREDITS'
  | 'AUTHENTICATION_REQUIRED'
  | 'AMBIGUOUS_RESOURCE'
  | 'CREDIT_OPERATION_FAILED'
  | 'CREDIT_REQUEST_STATE_CONFLICT'
  | 'EMAIL_ALREADY_REGISTERED'
  | 'FORBIDDEN'
  | 'IDEMPOTENCY_CONFLICT'
  | 'INVALID_CREDENTIALS'
  | 'INVALID_ACCESS_INVITATION'
  | 'INVALID_REQUEST'
  | 'INVALID_SUBMISSION_STATE'
  | 'INVALID_TRANSLATION_SOURCE'
  | 'INVALID_TRANSLATION_TRANSITION'
  | 'INTERNAL_ERROR'
  | 'INVALID_EMAIL_VERIFICATION'
  | 'LESSON_NOT_READY'
  | 'PUBLICATION_BLOCKED'
  | 'PUBLICATION_PLAN_STALE'
  | 'PUBLIC_LEADS_UNAVAILABLE'
  | 'PRICING_QUOTE_CONFLICT'
  | 'PRICING_QUOTE_EXPIRED'
  | 'PAYMENT_ALREADY_REFUNDED'
  | 'PAYMENT_DISPUTE_LOST'
  | 'PAYMENT_ORDER_NOT_FULFILLED'
  | 'PAYMENT_REFUND_PENDING'
  | 'PAYMENT_REFUND_PREVIEW_STALE'
  | 'PAYMENT_UNDER_DISPUTE'
  | 'ENTRY_TIER_ALREADY_PURCHASED'
  | 'PRICING_UNAVAILABLE'
  | 'PURCHASED_CREDITS_PROTECTED'
  | 'INVALID_PUBLIC_LEAD_TOKEN'
  | 'PROGRAM_VISIBILITY_CONFLICT'
  | 'REGISTRATION_DISABLED'
  | 'RESOURCE_NOT_FOUND'
  | 'SELF_SUSPENSION_NOT_ALLOWED'
  | 'TIMELINE_NOT_STARTED'
  | 'TOO_MANY_ACCESS_REQUESTS'
  | 'TOO_MANY_LOGIN_ATTEMPTS'
  | 'TRANSLATION_WORKFLOW_CONFLICT';

export interface ApiErrorBody {
  error: {
    code: ApiErrorCode;
    message: string;
  };
}

export class ApiError extends Error {
  public constructor(
    public readonly code: ApiErrorCode,
    message: string,
    public readonly status: ContentfulStatusCode,
  ) {
    super(message);
    this.name = 'ApiError';
  }
}

export function toApiErrorBody(error: ApiError): ApiErrorBody {
  return {
    error: {
      code: error.code,
      message: error.message,
    },
  };
}
import type { ContentfulStatusCode } from 'hono/utils/http-status';
