const sources = {
  openaiEvals: {
    type: 'website',
    title: 'Evals — OpenAI API documentation',
    author: 'OpenAI',
    url: 'https://developers.openai.com/api/docs/guides/evals',
    citation: 'OpenAI. (s. d.). Evals. OpenAI API documentation. Consulté le 18 août 2026.',
  },
  openaiEmbeddings: {
    type: 'website',
    title: 'Embeddings — OpenAI API documentation',
    author: 'OpenAI',
    url: 'https://developers.openai.com/api/docs/guides/embeddings',
    citation: 'OpenAI. (s. d.). Embeddings. OpenAI API documentation. Consulté le 18 août 2026.',
  },
  openaiRetrieval: {
    type: 'website',
    title: 'Retrieval — OpenAI API documentation',
    author: 'OpenAI',
    url: 'https://developers.openai.com/api/docs/guides/retrieval',
    citation: 'OpenAI. (s. d.). Retrieval. OpenAI API documentation. Consulté le 18 août 2026.',
  },
  openaiStructured: {
    type: 'website',
    title: 'Structured Outputs — OpenAI API documentation',
    author: 'OpenAI',
    url: 'https://developers.openai.com/api/docs/guides/structured-outputs',
    citation: 'OpenAI. (s. d.). Structured Outputs. OpenAI API documentation. Consulté le 18 août 2026.',
  },
  openaiSafety: {
    type: 'website',
    title: 'Safety best practices — OpenAI API documentation',
    author: 'OpenAI',
    url: 'https://developers.openai.com/api/docs/guides/safety-best-practices',
    citation: 'OpenAI. (s. d.). Safety best practices. OpenAI API documentation. Consulté le 18 août 2026.',
  },
  aiSdkEmbeddings: {
    type: 'website',
    title: 'Embeddings — AI SDK Core',
    author: 'Vercel',
    url: 'https://ai-sdk.dev/docs/ai-sdk-core/embeddings',
    citation: 'Vercel. (s. d.). Embeddings. AI SDK documentation. Consulté le 18 août 2026.',
  },
  aiSdkStructured: {
    type: 'website',
    title: 'Generating structured data — AI SDK Core',
    author: 'Vercel',
    url: 'https://ai-sdk.dev/docs/ai-sdk-core/generating-structured-data',
    citation: 'Vercel. (s. d.). Generating structured data. AI SDK documentation. Consulté le 18 août 2026.',
  },
  pgvector: {
    type: 'document',
    title: 'pgvector README',
    author: 'pgvector contributors',
    url: 'https://github.com/pgvector/pgvector',
    citation: 'pgvector contributors. (s. d.). pgvector. GitHub. Consulté le 18 août 2026.',
  },
  postgresTextSearch: {
    type: 'website',
    title: 'Controlling Text Search',
    author: 'PostgreSQL Global Development Group',
    url: 'https://www.postgresql.org/docs/current/textsearch-controls.html',
    citation: 'PostgreSQL Global Development Group. (2026). Controlling Text Search. PostgreSQL documentation.',
  },
  ragPaper: {
    type: 'article',
    title: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
    author: 'Patrick Lewis et al.',
    url: 'https://arxiv.org/abs/2005.11401',
    citation: 'Lewis, P., et al. (2020). Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks. Advances in Neural Information Processing Systems, 33.',
  },
  sbertPaper: {
    type: 'article',
    title: 'Sentence-BERT: Sentence Embeddings using Siamese BERT-Networks',
    author: 'Nils Reimers et Iryna Gurevych',
    url: 'https://arxiv.org/abs/1908.10084',
    citation: 'Reimers, N., & Gurevych, I. (2019). Sentence-BERT: Sentence Embeddings using Siamese BERT-Networks. EMNLP-IJCNLP 2019.',
  },
  beirPaper: {
    type: 'article',
    title: 'BEIR: A Heterogeneous Benchmark for Zero-shot Evaluation of Information Retrieval Models',
    author: 'Nandan Thakur et al.',
    url: 'https://arxiv.org/abs/2104.08663',
    citation: 'Thakur, N., et al. (2021). BEIR: A Heterogeneous Benchmark for Zero-shot Evaluation of Information Retrieval Models. NeurIPS Datasets and Benchmarks.',
  },
  nistAiRmf: {
    type: 'document',
    title: 'Artificial Intelligence Risk Management Framework (AI RMF 1.0)',
    author: 'National Institute of Standards and Technology',
    url: 'https://www.nist.gov/itl/ai-risk-management-framework',
    citation: 'National Institute of Standards and Technology. (2023). Artificial Intelligence Risk Management Framework (AI RMF 1.0).',
  },
  nistGenAi: {
    type: 'document',
    title: 'Artificial Intelligence Risk Management Framework: Generative Artificial Intelligence Profile',
    author: 'National Institute of Standards and Technology',
    url: 'https://doi.org/10.6028/NIST.AI.600-1',
    citation: 'National Institute of Standards and Technology. (2024). Artificial Intelligence Risk Management Framework: Generative Artificial Intelligence Profile (NIST AI 600-1). https://doi.org/10.6028/NIST.AI.600-1',
  },
  owaspPromptInjection: {
    type: 'article',
    title: 'LLM01: Prompt Injection',
    author: 'OWASP GenAI Security Project',
    url: 'https://genai.owasp.org/llmrisk/llm01-prompt-injection/',
    citation: 'OWASP GenAI Security Project. (s. d.). LLM01: Prompt Injection. Consulté le 18 août 2026.',
  },
  cmuObjectives: {
    type: 'article',
    title: 'Designing Learning Objectives',
    author: 'Carnegie Mellon University Eberly Center',
    url: 'https://www.cmu.edu/teaching/designteach/design/learningobjectives.html',
    citation: 'Carnegie Mellon University Eberly Center. (s. d.). Designing Learning Objectives. Consulté le 18 août 2026.',
  },
  cmuAssessments: {
    type: 'article',
    title: 'Assessing Student Learning',
    author: 'Carnegie Mellon University Eberly Center',
    url: 'https://www.cmu.edu/teaching/designteach/design/assessments.html',
    citation: 'Carnegie Mellon University Eberly Center. (s. d.). Assessing Student Learning. Consulté le 18 août 2026.',
  },
  cornellRubrics: {
    type: 'article',
    title: 'Using Rubrics',
    author: 'Cornell University Center for Teaching Innovation',
    url: 'https://teaching.cornell.edu/teaching-resources/assessment-evaluation/using-rubrics',
    citation: 'Cornell University Center for Teaching Innovation. (s. d.). Using Rubrics. Consulté le 18 août 2026.',
  },
  jsonSchema: {
    type: 'website',
    title: 'JSON Schema — Getting started step by step',
    author: 'JSON Schema',
    url: 'https://json-schema.org/learn/getting-started-step-by-step',
    citation: 'JSON Schema. (s. d.). Getting started step by step. Consulté le 18 août 2026.',
  },
  learnxEditorial: {
    type: 'document',
    title: 'Gouvernance éditoriale — LearnX',
    author: 'LearnX',
    url: 'https://github.com/Guts6667/learnx/blob/main/EDITORIAL_GUIDELINES.md',
    citation: 'LearnX. (2026). Gouvernance éditoriale — LearnX. Version consultée le 18 août 2026.',
  },
  learnxAuthoring: {
    type: 'document',
    title: 'Guide de rédaction des PEDAGOGY_SPEC — LearnX',
    author: 'LearnX',
    url: 'https://github.com/Guts6667/learnx/blob/main/PEDAGOGY_AUTHORING_GUIDE.md',
    citation: 'LearnX. (2026). Guide de rédaction des PEDAGOGY_SPEC — LearnX. Version consultée le 18 août 2026.',
  },
  langfuseObservability: {
    type: 'website',
    title: 'LLM Observability',
    author: 'Langfuse',
    url: 'https://langfuse.com/docs/observability/overview',
    citation: 'Langfuse. (s. d.). LLM Observability. Consulté le 18 août 2026.',
  },
  langfuseEvaluation: {
    type: 'website',
    title: 'Evaluation',
    author: 'Langfuse',
    url: 'https://langfuse.com/docs/evaluation/overview',
    citation: 'Langfuse. (s. d.). Evaluation. Consulté le 18 août 2026.',
  },
  otelTracing: {
    type: 'website',
    title: 'Traces',
    author: 'OpenTelemetry',
    url: 'https://opentelemetry.io/docs/concepts/signals/traces/',
    citation: 'OpenTelemetry. (s. d.). Traces. Consulté le 18 août 2026.',
  },
};

function resource(source, key, description, objective, instructions, scope, minutes = 18, isRequired = true) {
  return { ...source, key, description, objective, instructions, scope, minutes, isRequired };
}

function stageAssessment(title, description, instructions, criteria, type = 'practical_exercise') {
  return {
    title,
    type,
    isRequired: true,
    passingScore: 75,
    description,
    instructions,
    rubric: criteria,
  };
}

const sourceLabPrerequisite = ['Avoir terminé « SourceLab — Socle d’ingénierie en production » ou disposer d’un dépôt équivalent avec API, worker, PostgreSQL, tests et observabilité de base.'];

export const aiDefinition = {
  title: 'SourceLab — RAG, génération et évaluation IA',
  slug: 'sourcelab-ia-rag',
  seedFile: 'sourcelab-ai-rag-program.json',
  position: 6,
  estimatedDurationDays: 56,
  audience: 'Product engineer ou développeur TypeScript capable d’exploiter un petit service en production et souhaitant construire des fonctionnalités IA mesurées.',
  description: 'Parcours pratique de huit semaines pour transformer SourceLab en laboratoire de produits IA fiables. Le programme construit une couche documentaire RAG puis deux verticales seulement : un Program Builder qui produit des brouillons LearnX sourcés et modifiables, et un Assessment Reviewer qui propose un feedback structuré sur les réponses libres. Les décisions reposent sur des datasets, des évaluations, une provenance et des seuils de revue humaine.',
  productPromise: 'SourceLab aide un créateur à transformer un besoin et des matériaux en blueprint puis programme LearnX, et aide un évaluateur à analyser une réponse libre avec une grille et des sources contrôlées. Il génère des propositions ; LearnX reste l’autorité de publication, progression et note finale.',
  cumulativeDeliverable: 'Le même dépôt SourceLab enrichi d’un pipeline d’ingestion et d’indexation, d’un benchmark de retrieval, d’un Program Builder, d’un Assessment Reviewer, de datasets d’évaluation, de traces, d’un threat model et de contrats d’export/API. La base SourceLab reste indépendante de LearnX.',
  finality: 'Apprendre le RAG, les sorties structurées et l’évaluation en construisant deux usages produits précis. Le parcours refuse le chatbot générique, la génération monolithique et la note automatique non contrôlée. Chaque étape ajoute une capacité mesurable au Source Pack et aux deux verticales.',
  startingProfile: 'L’apprenant maîtrise TypeScript et possède le socle SourceLab V1 : import, jobs, worker, PostgreSQL, Docker, tests d’intégration, CI et observabilité. Il connaît les usages généraux des LLM, mais n’a pas encore construit de retrieval évalué ni de système de correction fiable.',
  learningOutcomes: [
    'formuler les contrats produit, datasets et critères d’acceptation des deux fonctions IA ;',
    'ingérer, segmenter, versionner et représenter des sources avec une provenance conservée ;',
    'comparer recherche lexicale, vectorielle, hybride, filtres, reranking et abstention ;',
    'générer un brief, un blueprint et un programme LearnX structurés sans réécrire les parties verrouillées ;',
    'proposer une correction de texte libre critère par critère et mesurer sa cohérence face à une référence humaine ;',
    'sécuriser les entrées documentaires, observer coût et latence et préparer une intégration LearnX versionnée.',
  ],
  outOfScope: [
    'entraîner un modèle fondation ou devenir machine learning engineer ;',
    'publier automatiquement un programme ou attribuer une note définitive dans LearnX ;',
    'construire un chatbot généraliste sur tous les contenus ;',
    'partager la base SourceLab avec LearnX ou modifier son dépôt dans le cadre du projet fil rouge ;',
    'multiplier les agents ou fournisseurs avant d’avoir une baseline et des évaluations.',
  ],
  stages: [
    {
      title: 'Cadrer les usages et les preuves',
      slug: 'cadrer-usages-evaluations',
      moduleTitle: 'Contrats produit et datasets',
      moduleSlug: 'contrats-evals',
      days: 8,
      productOutcome: 'un contrat mesurable pour Program Builder et Assessment Reviewer, accompagné d’une baseline sans RAG et d’un dataset initial.',
      assessment: stageAssessment(
        'Évaluation — Définir le contrat de qualité IA',
        'Transformer les deux usages SourceLab en décisions évaluables avant de choisir le pipeline ou le modèle.',
        'Décrire utilisateurs, intent, entrées, sorties, erreurs acceptables et autorité finale des deux verticales. Construire un dataset initial comprenant cas normaux, absents, ambigus et adversariaux. Exécuter une baseline simple sans retrieval, analyser ses erreurs et définir les seuils nécessaires pour poursuivre ou arrêter.',
        [
          { criterion: 'Contrat produit', weight: 25, requirements: ['Les deux usages et leurs non-objectifs sont distincts.', 'Les décisions finales de LearnX et humaines restent explicites.'] },
          { criterion: 'Dataset', weight: 30, requirements: ['Les cas représentent les risques réels et pas seulement le chemin heureux.', 'La provenance et les attentes sont versionnées.'] },
          { criterion: 'Métriques et seuils', weight: 25, requirements: ['Retrieval, génération et décision produit sont séparés.', 'Des conditions de non-poursuite sont définies.'] },
          { criterion: 'Analyse de baseline', weight: 20, requirements: ['Les erreurs sont catégorisées avec exemples.', 'Aucune amélioration n’est affirmée sans comparaison.'] },
        ],
        'case_study',
      ),
      lessons: [
        {
          title: 'Définir les contrats des deux fonctions IA',
          slug: 'definir-contrats-fonctions-ia',
          minutes: 110,
          prerequisites: sourceLabPrerequisite,
          summary: 'Passer de « ajouter de l’IA » à deux expériences, sorties et autorités explicitement mesurables.',
          objectives: ['Décrire l’intent et la décision de chaque verticale.', 'Séparer proposition IA et autorité produit.', 'Identifier les échecs qui doivent déclencher abstention ou revue humaine.'],
          explanation: 'Le Program Builder transforme un besoin, des réponses au funnel et un Source Pack en brief, blueprint puis brouillon LearnX. L’Assessment Reviewer reçoit une consigne, une rubrique, un contexte autorisé et une réponse ; il propose un résultat par critère. Dans les deux cas, le modèle n’est pas l’autorité : SourceLab conserve entrées, version et provenance, tandis que l’utilisateur valide la structure et LearnX décide publication ou résultat final. Les exigences de qualité portent sur des décisions observables, pas sur une impression de fluidité.',
          example: 'Une génération produit un programme grammaticalement convaincant mais ajoute une certification non demandée et une source inexistante. Le contrat doit compter cet échec comme critique même si le texte paraît excellent. À l’inverse, une correction prudente qui demande une revue humaine faute de source peut être un succès produit.',
          resources: [
            resource(sources.openaiEvals, 'openai-evals-contracts', 'Lire le cycle de création d’une évaluation et la définition de critères avant de constituer le dataset SourceLab.', 'Transformer un comportement attendu en exemples et graders.', 'Lire l’introduction et le workflow de création d’evals ; noter ce qui doit être défini avant l’appel modèle.', 'Introduction et workflow principal', 20),
            resource(sources.nistAiRmf, 'nist-ai-rmf-contracts', 'Utiliser les fonctions Govern, Map, Measure et Manage comme grille de questions, sans transformer le parcours en audit de conformité.', 'Relier usage, contexte, mesure et traitement du risque.', 'Lire la présentation du cadre et relever les questions utiles à la finalité, aux parties affectées, à la mesure et au suivi.', 'Présentation générale et Core', 22),
          ],
          readingDescription: 'Rédiger deux fiches intent → utilisateur → entrées autorisées → sortie → autorité → erreur critique → fallback → métrique.',
          exerciseTitle: 'Écrire les contrats Program Builder et Assessment Reviewer',
          exerciseDescription: 'Produire deux contrats JSON Schema ou Zod accompagnés d’un tableau de décisions. Inclure PROGRAM_DRAFT_READY, NEEDS_MORE_CONTEXT, HUMAN_CONFIRMATION_REQUIRED, HUMAN_REVIEW_REQUIRED et INSUFFICIENT_EVIDENCE, puis écrire un cas qui doit conduire à chacun.',
          concept: {
            title: 'Contrat IA orienté décision',
            slug: 'contrat-ia-oriente-decision',
            description: 'Un contrat IA orienté décision définit l’intent, les données autorisées, la sortie structurée, l’autorité finale, les échecs critiques et le fallback avant de choisir modèle ou prompt.',
            misconception: 'Une bonne fonctionnalité IA est une conversation naturelle qui produit généralement une réponse utile.',
            trueStatement: 'Une abstention peut être un résultat correct lorsque les preuves autorisées ne permettent pas la décision.',
            falseStatement: 'Le score de confiance déclaré par le modèle suffit à décider d’une validation automatique.',
            scenarioPrompt: 'Le correcteur ne retrouve aucune source sur le critère principal. Quel résultat respecte le contrat ?',
            scenarioCorrect: 'INSUFFICIENT_EVIDENCE ou HUMAN_REVIEW_REQUIRED, avec le critère non évalué.',
            scenarioDistractors: ['Inventer une référence probable.', 'Noter selon la longueur de la réponse.', 'Valider par défaut pour préserver l’expérience.'],
            requiredItems: ['autorité finale explicite', 'erreurs critiques', 'fallback observable'],
            badItems: ['sortie libre non validée', 'confiance auto-déclarée comme seule règle'],
            shortPrompt: 'Distingue la proposition produite par SourceLab de la décision conservée par LearnX.',
            acceptedAnswers: ['SourceLab propose LearnX valide stocke décide', 'suggestion IA autorité finale LearnX humain'],
            decisionRule: 'Définir d’abord la décision que le produit doit prendre ou refuser ; le modèle n’est qu’un composant remplaçable de cette décision.',
          },
        },
        {
          title: 'Construire baseline, dataset et seuils',
          slug: 'construire-baseline-dataset-seuils',
          minutes: 125,
          prerequisites: ['Avoir défini les deux contrats IA SourceLab.'],
          summary: 'Créer des exemples représentatifs et mesurer une solution simple avant d’ajouter retrieval, reranking ou agent.',
          objectives: ['Construire un golden dataset versionné.', 'Séparer métriques de composant et résultat produit.', 'Comparer toute amélioration à une baseline.'],
          explanation: 'Un dataset utile contient des entrées, le contexte autorisé, le résultat attendu, les critères et la raison de l’attente. Il inclut questions répondables, absentes, paraphrasées, contradictoires et tentatives d’injection ; pour l’évaluation libre, réponses correctes atypiques, verbeuses, lacunaires et hors sujet. La baseline peut envoyer un contexte fixe ou n’utiliser que la rubrique. Son but n’est pas d’être excellente, mais de rendre visible ce que le RAG devra améliorer et ce qu’il peut dégrader.',
          example: 'SourceLab évalue vingt réponses. Le modèle sans retrieval attribue des scores cohérents sur les réponses évidentes, mais invente les critères implicites et pénalise les réponses courtes. Ces erreurs deviennent des catégories et des cas de non-régression plutôt qu’une motivation vague pour « ajouter du RAG ».',
          resources: [
            resource(sources.openaiEvals, 'openai-evals-datasets', 'Étudier datasets, graders et exécutions répétables avant de versionner les cas SourceLab.', 'Construire une évaluation rejouable.', 'Lire les sections sur les données de test, graders et exécution ; définir les champs obligatoires d’un cas.', 'Datasets, graders et runs', 22),
            resource(sources.beirPaper, 'beir-evaluation-ir', 'Lire abstract, motivation et diversité des datasets pour comprendre pourquoi une seule collection homogène surestime un retriever.', 'Diversifier les cas et domaines d’évaluation.', 'Lire abstract, introduction et tableau des datasets ; relever trois formes d’hétérogénéité à reproduire à petite échelle.', 'Abstract, introduction et datasets', 22),
          ],
          readingDescription: 'Créer la taxonomie des cas et une fiche de version indiquant source, auteur de la référence, critères, date et modifications.',
          exerciseTitle: 'Créer le dataset SourceLab v0 et exécuter la baseline',
          exerciseDescription: 'Authorer au moins 20 cas Program Builder et 30 réponses Assessment Reviewer. Exécuter une baseline déterministe, calculer succès par critère, taux d’abstention et erreurs critiques, puis fixer les seuils nécessaires avant passage à l’ingestion.',
          concept: {
            title: 'Dataset d’évaluation représentatif',
            slug: 'dataset-evaluation-representatif',
            description: 'Un dataset d’évaluation représentatif échantillonne les décisions, difficultés, absences de preuve et attaques que le produit rencontrera, avec des attentes versionnées et revues.',
            misconception: 'Dix exemples rédigés après avoir vu les réponses du modèle suffisent à prouver la qualité.',
            trueStatement: 'Un cas d’information absente est nécessaire pour mesurer l’abstention et les hallucinations.',
            falseStatement: 'Le dataset doit contenir uniquement des cas faciles afin de détecter rapidement les régressions.',
            scenarioPrompt: 'Le retriever est évalué seulement sur des questions reprenant les mots exacts des titres. Quel risque apparaît ?',
            scenarioCorrect: 'La mesure surestime la recherche sémantique et ne teste ni paraphrases ni ambiguïtés.',
            scenarioDistractors: ['Les embeddings deviennent plus chers.', 'Le JSON Schema cesse de fonctionner.', 'Les containers perdent leur volume.'],
            requiredItems: ['cas normaux et limites', 'attentes revues', 'version et provenance'],
            badItems: ['sélection après observation des résultats', 'métrique unique sans erreur critique'],
            shortPrompt: 'Cite quatre catégories indispensables du dataset SourceLab.',
            acceptedAnswers: ['répondable absent ambigu adversarial', 'normal paraphrase contradictoire injection'],
            decisionRule: 'Construire le test à partir du risque produit, puis figer sa version avant de choisir la configuration qui sera comparée.',
          },
        },
      ],
    },
    {
      title: 'Ingestion et représentation documentaire',
      slug: 'ingerer-representer-documents',
      moduleTitle: 'Provenance, chunks et vecteurs',
      moduleSlug: 'provenance-chunks-vecteurs',
      days: 10,
      productOutcome: 'un Source Pack indexé où chaque chunk conserve document, version, section, droits et localisateur.',
      assessment: stageAssessment(
        'Évaluation — Indexer un Source Pack traçable',
        'Transformer un corpus hétérogène en chunks et embeddings sans perdre la provenance ni mélanger les versions.',
        'Importer textes, pages et fichiers de test, normaliser les métadonnées, comparer deux stratégies de chunking, générer les embeddings en lots et stocker vecteur, modèle, dimension, version et localisateur. Rejouer un document inchangé, remplacer une version et démontrer que les chunks obsolètes ne sont plus récupérables.',
        [
          { criterion: 'Provenance', weight: 30, requirements: ['Chaque chunk remonte à une source, version et section.', 'Les droits et statuts éditoriaux restent filtrables.'] },
          { criterion: 'Chunking', weight: 25, requirements: ['Deux stratégies sont comparées sur des cas réels.', 'Les frontières sémantiques et la taille sont mesurées.'] },
          { criterion: 'Embeddings', weight: 25, requirements: ['Modèle, dimension et version sont persistés.', 'L’ingestion rejouée est idempotente.'] },
          { criterion: 'Cycle de vie', weight: 20, requirements: ['Une nouvelle version désactive proprement l’ancienne.', 'Les échecs partiels sont repris sans mélange.'] },
        ],
      ),
      lessons: [
        {
          title: 'Extraire, normaliser et segmenter avec provenance',
          slug: 'extraire-normaliser-segmenter',
          minutes: 135,
          prerequisites: ['Disposer du dataset SourceLab v0.'],
          summary: 'Construire des chunks utiles au retrieval sans perdre le document, la section, la version ou le rôle éditorial.',
          objectives: ['Définir le contrat d’un chunk.', 'Comparer chunking fixe et structuré.', 'Versionner extraction et normalisation.'],
          explanation: 'Le chunk n’est pas seulement un texte : il porte documentId, versionId, section, ordre, offsets ou localisateur, langue, rôle, droits et version du pipeline. Le chunking fixe simplifie les lots mais peut couper une définition de son exemple ; le chunking par structure respecte titres et blocs, puis subdivise les sections trop longues. Le chevauchement peut préserver le contexte au prix de doublons. Toute normalisation doit rester reproductible et ne pas supprimer les éléments nécessaires à une citation.',
          example: 'Une ressource LearnX contient un titre, une définition, un exemple et une consigne. Des tranches de 500 caractères séparent le terme de sa définition et du sourceKey. La stratégie structurée crée un chunk par bloc, ajoute le chemin programme/étape/leçon et conserve la clé immuable pour ouvrir le bon passage.',
          resources: [
            resource(sources.openaiRetrieval, 'openai-retrieval-chunking', 'Lire la description de l’indexation, des attributs et des options de chunking afin d’identifier les métadonnées nécessaires.', 'Relier préparation du document et récupération future.', 'Lire Vector stores, Search et Chunking ; noter les paramètres qui changent la recherche et ceux qui doivent être versionnés.', 'Vector stores, Search et Chunking', 24),
            resource(sources.ragPaper, 'rag-paper-provenance', 'Lire abstract, introduction et architecture générale pour situer le retriever et les passages externes dans la génération.', 'Comprendre la séparation mémoire paramétrique / non paramétrique.', 'Lire abstract, sections 1 et 2 ; dessiner ce que SourceLab stocke hors modèle et ce qui est envoyé au générateur.', 'Abstract, sections 1 et 2', 24),
          ],
          readingDescription: 'Écrire le schéma Chunk et lister les transformations réversibles, pertes acceptées et localisateurs nécessaires aux citations.',
          exerciseTitle: 'Comparer deux stratégies de chunking',
          exerciseDescription: 'Implémenter chunking fixe et chunking par structure sur dix sources. Produire nombre de chunks, taille moyenne/p95, coupures de notion et doublons. Choisir une stratégie par type de document et enregistrer pipelineVersion.',
          concept: {
            title: 'Chunk traçable',
            slug: 'chunk-tracable',
            description: 'Un chunk traçable associe un passage exploitable à sa source, sa version, sa position, ses droits et la version du pipeline qui l’a produit.',
            misconception: 'Un chunk est uniquement une chaîne optimisée pour tenir dans la fenêtre de contexte.',
            trueStatement: 'Conserver le chemin de section permet d’afficher une citation plus précise et d’améliorer certains filtres.',
            falseStatement: 'Plus les chunks sont petits, meilleure est toujours la précision du retriever.',
            scenarioPrompt: 'Une définition et son exception sont séparées par une tranche fixe. Quelle amélioration tester ?',
            scenarioCorrect: 'Respecter la structure de section puis subdiviser seulement les blocs trop longs.',
            scenarioDistractors: ['Supprimer tous les titres.', 'Augmenter le top-k sans mesurer.', 'Mélanger les versions du document.'],
            requiredItems: ['source et version', 'localisateur', 'pipelineVersion'],
            badItems: ['texte sans provenance', 'ancienne version encore active sans filtre'],
            shortPrompt: 'Quels champs minimaux permettent de citer et réindexer un chunk ?',
            acceptedAnswers: ['document version section position texte pipeline', 'sourceId versionId locator order pipelineVersion'],
            decisionRule: 'Optimiser la taille sans sacrifier l’unité de sens ni la capacité à expliquer précisément d’où vient le passage.',
          },
        },
        {
          title: 'Produire et stocker des embeddings avec pgvector',
          slug: 'produire-stocker-embeddings-pgvector',
          minutes: 140,
          prerequisites: ['Avoir un contrat de chunk versionné.'],
          summary: 'Transformer chunks et requêtes dans le même espace vectoriel et conserver les paramètres nécessaires à une comparaison honnête.',
          objectives: ['Expliquer similarité et limites d’un embedding.', 'Générer des embeddings en lots.', 'Stocker modèle, dimension et index sans masquer le SQL.'],
          explanation: 'Un embedding représente un texte par un vecteur utile à une mesure de proximité, pas par une vérité ou une preuve de compréhension. Chunks et requêtes doivent utiliser le même modèle et la même dimension. L’ingestion en lots réduit les appels mais doit rattacher chaque résultat à son chunk. PostgreSQL avec pgvector stocke les vecteurs et calcule différentes distances ; l’index approximatif accélère certaines recherches en échange d’un compromis de rappel et de paramètres à mesurer. Les filtres de droits restent des conditions de données, pas des consignes au modèle.',
          example: 'SourceLab change de modèle d’embedding sans réindexer le corpus. Les nouvelles requêtes ont la même dimension mais un espace différent : les scores deviennent sans sens. Le schéma conserve embeddingModel et embeddingVersion, crée un nouvel index logique puis bascule seulement après comparaison.',
          resources: [
            resource(sources.openaiEmbeddings, 'openai-embeddings-guide', 'Lire usages, création et limites opérationnelles des embeddings avant de définir le batch SourceLab.', 'Générer des vecteurs avec un modèle explicitement versionné.', 'Lire l’introduction et les exemples de création ; noter modèle, dimension, limites et ordre de retour.', 'Introduction et création d’embeddings', 22),
            resource(sources.pgvector, 'pgvector-readme', 'Lire stockage, opérateurs de distance et index HNSW/IVFFlat avant d’écrire la migration.', 'Choisir une requête vectorielle mesurable dans PostgreSQL.', 'Lire Getting started, Querying, Indexing et Filtering ; écrire la requête exacte avec filtre de projet.', 'Getting started, Querying, Indexing et Filtering', 28),
          ],
          readingDescription: 'Écrire la fiche embeddingModel, dimension, distance, batch, retry, coût, index et stratégie de réindexation.',
          exerciseTitle: 'Indexer et interroger les chunks SourceLab',
          exerciseDescription: 'Ajouter pgvector par migration, générer les embeddings en lots et implémenter une recherche exacte filtrée par projectId/version active. Comparer ensuite un index approximatif sur un corpus synthétique et documenter latence, rappel et paramètres.',
          concept: {
            title: 'Espace vectoriel versionné',
            slug: 'espace-vectoriel-versionne',
            description: 'Un espace vectoriel versionné associe modèle, dimension, préparation du texte et métrique afin que chunks et requêtes restent comparables et réindexables.',
            misconception: 'Deux modèles produisant des vecteurs de même dimension peuvent être mélangés dans le même index.',
            trueStatement: 'Un score de similarité élevé signale une proximité selon le modèle, pas la vérité du passage.',
            falseStatement: 'L’index HNSW améliore toujours la qualité des résultats par rapport à une recherche exacte.',
            scenarioPrompt: 'SourceLab change de modèle d’embedding. Quelle stratégie est correcte ?',
            scenarioCorrect: 'Créer une nouvelle version d’index, réencoder corpus et requêtes, comparer puis basculer.',
            scenarioDistractors: ['Réencoder seulement les requêtes.', 'Conserver les anciens vecteurs sans métadonnée.', 'Multiplier tous les scores par deux.'],
            requiredItems: ['modèle et dimension', 'même pipeline requête/corpus', 'plan de réindexation'],
            badItems: ['vecteurs sans version', 'droits confiés au prompt'],
            shortPrompt: 'Pourquoi faut-il conserver le modèle et la version de chaque embedding ?',
            acceptedAnswers: ['comparabilité réindexation même espace', 'éviter mélange modèles reproduire recherche'],
            decisionRule: 'Aucun score vectoriel n’est interprétable sans connaître le modèle, le texte préparé, la distance et la population comparée.',
          },
        },
      ],
    },
    {
      title: 'Récupérer les preuves utiles',
      slug: 'recuperer-preuves-utiles',
      moduleTitle: 'Recherche hybride et abstention',
      moduleSlug: 'recherche-hybride-abstention',
      days: 10,
      productOutcome: 'un retriever benchmarké qui respecte projets et versions, cite les passages et sait ne rien retourner lorsque les preuves sont insuffisantes.',
      assessment: stageAssessment(
        'Évaluation — Choisir le retriever SourceLab',
        'Comparer plusieurs pipelines sur le dataset figé et défendre une configuration de départ.',
        'Exécuter recherche lexicale, vectorielle et hybride avec les mêmes cas. Mesurer présence de la bonne source, rang, latence et absence de fuite. Ajouter filtres, top-k, fusion ou reranking, puis calibrer un seuil d’abstention. Produire un rapport erreurs → changement → résultat → coût et refuser toute conclusion non soutenue.',
        [
          { criterion: 'Protocole', weight: 25, requirements: ['Dataset, version et métriques sont identiques entre variantes.', 'Les résultats sont reproductibles.'] },
          { criterion: 'Qualité du retrieval', weight: 30, requirements: ['Lexical, vectoriel et hybride sont comparés.', 'Les erreurs de rang, filtre et absence sont séparées.'] },
          { criterion: 'Sécurité et abstention', weight: 25, requirements: ['Les droits sont appliqués avant retour des chunks.', 'Le seuil réduit les réponses sans preuve sans cacher son coût de rappel.'] },
          { criterion: 'Décision', weight: 20, requirements: ['Qualité, latence et coût sont arbitrés.', 'La configuration la plus complexe n’est pas choisie automatiquement.'] },
        ],
      ),
      lessons: [
        {
          title: 'Comparer recherche lexicale, vectorielle et hybride',
          slug: 'comparer-recherche-lexicale-vectorielle-hybride',
          minutes: 135,
          prerequisites: ['Avoir indexé le Source Pack et figé un dataset de retrieval.'],
          summary: 'Comprendre ce que chaque famille retrouve ou manque avant de fusionner ses résultats.',
          objectives: ['Construire une recherche plein texte PostgreSQL.', 'Comparer métriques et erreurs au vectoriel.', 'Fusionner sans double compter les chunks.'],
          explanation: 'La recherche lexicale valorise les termes exacts, identifiants, noms de commandes et expressions rares ; la vectorielle retrouve mieux certaines paraphrases. L’hybride combine deux listes comparables par rang ou score normalisé. Une fusion doit dédupliquer les chunks et rester évaluée sur le même corpus. Pour SourceLab, les références techniques, versions et slugs peuvent favoriser le lexical alors que les formulations de besoin et réponses libres bénéficient davantage du sémantique.',
          example: 'La question « Pourquoi mon worker reprend-il deux fois le même fichier ? » ne contient pas le mot idempotence, mais le vectoriel retrouve la leçon. La requête « SIGTERM » est mieux servie par le lexical. La fusion place les deux passages dans le top 5, puis l’évaluation vérifie lequel est réellement pertinent.',
          resources: [
            resource(sources.postgresTextSearch, 'postgres-text-search-controls', 'Lire to_tsvector, plainto_tsquery, websearch_to_tsquery et ranking avant de construire la baseline lexicale.', 'Créer une recherche plein texte explicable.', 'Lire Parsing Documents, Parsing Queries et Ranking Search Results ; implémenter une requête filtrée par projectId.', 'Sections 12.3.1 à 12.3.3', 28),
            resource(sources.pgvector, 'pgvector-hybrid-reference', 'Relire Hybrid Search et Filtering afin de combiner plein texte et vecteurs dans PostgreSQL.', 'Comparer et fusionner deux listes de candidats.', 'Lire Hybrid Search et Filtering ; choisir une méthode de fusion et documenter ses paramètres.', 'Hybrid Search et Filtering', 18),
          ],
          readingDescription: 'Écrire les hypothèses : quels cas devraient favoriser lexical, vectoriel ou hybride, puis figer les métriques avant exécution.',
          exerciseTitle: 'Exécuter le benchmark des trois recherches',
          exerciseDescription: 'Implémenter lexical, vectoriel exact et fusion hybride. Mesurer recall@k, MRR ou rang de la bonne source, latence et erreurs par catégorie. Publier les dix cas où chaque approche gagne ou échoue.',
          concept: {
            title: 'Recherche hybride évaluée',
            slug: 'recherche-hybride-evaluee',
            description: 'Une recherche hybride évaluée combine des signaux lexicaux et sémantiques selon une règle explicite, puis mesure le gain et les régressions sur un dataset figé.',
            misconception: 'Additionner les scores plein texte et cosinus produit automatiquement un classement comparable.',
            trueStatement: 'Les termes rares, codes et identifiants peuvent favoriser le lexical même dans un produit RAG.',
            falseStatement: 'L’hybride est nécessairement meilleur sur chaque requête individuelle.',
            scenarioPrompt: 'Une requête contient exactement un slug de leçon. Quel signal mérite une forte considération ?',
            scenarioCorrect: 'Le signal lexical, tout en conservant le filtre et la comparaison au vectoriel.',
            scenarioDistractors: ['La longueur du prompt système.', 'Le nombre de containers.', 'Un score de confiance inventé par le modèle.'],
            requiredItems: ['fusion explicite', 'déduplication', 'mêmes cas et métriques'],
            badItems: ['scores additionnés sans normalisation', 'choix après lecture sélective des résultats'],
            shortPrompt: 'Donne un cas SourceLab favorable au lexical et un favorable au vectoriel.',
            acceptedAnswers: ['SIGTERM lexical paraphrase idempotence vectoriel', 'slug exact lexical formulation différente vectorielle'],
            decisionRule: 'Combiner les signaux uniquement lorsque leurs erreurs complémentaires sont observées et que la fusion améliore le résultat produit mesuré.',
          },
        },
        {
          title: 'Filtrer, reranker et décider de s’abstenir',
          slug: 'filtrer-reranker-abstention',
          minutes: 145,
          prerequisites: ['Avoir comparé les recherches sur le même dataset.'],
          summary: 'Séparer éligibilité, rappel de candidats, classement final et décision de fournir du contexte.',
          objectives: ['Appliquer les permissions avant le ranking final.', 'Mesurer top-k et reranking.', 'Calibrer une abstention avec coût de faux négatif.'],
          explanation: 'Le filtre détermine quels chunks sont autorisés : projet, version active, langue, rôle, statut éditorial et droits. Le retriever vise d’abord un rappel suffisant avec un top-k de candidats ; un reranker plus coûteux peut ensuite réordonner une petite liste. Le seuil d’abstention ne se choisit pas sur l’intuition d’un score : on observe distributions des cas répondables et absents, puis on arbitre hallucinations évitées et réponses utiles perdues. Si aucune preuve ne passe, la génération reçoit explicitement un contexte vide.',
          example: 'Le meilleur score global appartient à un autre projet de l’utilisateur. Le prompt « n’utilise que le projet courant » ne constitue pas un contrôle d’accès. La requête SQL filtre d’abord projectId et version, puis le reranker ne voit que des candidats autorisés. Un cas sans passage suffisant renvoie NEEDS_MORE_CONTEXT avant tout texte de réponse.',
          resources: [
            resource(sources.openaiRetrieval, 'openai-retrieval-ranking', 'Lire attribut filtering, ranking options et score threshold afin de distinguer éligibilité et pertinence.', 'Configurer recherche, filtres et seuil de manière mesurable.', 'Lire Attribute filtering et Ranking options ; reproduire les paramètres dans la fiche d’expérience SourceLab.', 'Attribute filtering et Ranking options', 24),
            resource(sources.beirPaper, 'beir-zero-shot-errors', 'Revoir la diversité des tâches et résultats afin de ne pas généraliser un réglage top-k depuis un seul type de question.', 'Tester le ranking sur des requêtes hétérogènes.', 'Lire les résultats et limitations ; noter pourquoi un même modèle ou réglage varie selon la tâche.', 'Results et limitations', 20),
          ],
          readingDescription: 'Dessiner les quatre portes : autorisation → candidats → reranking → abstention, avec métrique et propriétaire pour chacune.',
          exerciseTitle: 'Calibrer top-k, reranking et seuil',
          exerciseDescription: 'Tester au moins trois top-k, avec et sans reranking. Ajouter cas inter-projets et informations absentes. Tracer rappel, précision des citations, latence et taux d’abstention, puis choisir un seuil et documenter les cas perdus.',
          concept: {
            title: 'Abstention fondée sur les preuves',
            slug: 'abstention-fondee-preuves',
            description: 'L’abstention fondée sur les preuves refuse de générer une conclusion lorsque les passages autorisés et pertinents ne franchissent pas un seuil calibré sur des cas répondables et absents.',
            misconception: 'Demander au modèle s’il est confiant remplace un seuil de retrieval et une revue humaine.',
            trueStatement: 'Les permissions doivent être appliquées avant d’envoyer les candidats au reranker ou au modèle.',
            falseStatement: 'Augmenter top-k améliore toujours la réponse sans coût ni bruit.',
            scenarioPrompt: 'Le meilleur passage vient d’un projet non autorisé. Quelle action est correcte ?',
            scenarioCorrect: 'L’exclure par filtre de données avant ranking et génération.',
            scenarioDistractors: ['Le transmettre puis demander au modèle de l’ignorer.', 'Masquer seulement sa citation.', 'L’utiliser si son score dépasse 0,9.'],
            requiredItems: ['filtre d’éligibilité', 'seuil calibré', 'fallback explicite'],
            badItems: ['permission dans le prompt', 'top-k maximal sans mesure'],
            shortPrompt: 'Comment calibrer un seuil d’abstention ?',
            acceptedAnswers: ['comparer scores répondables absents arbitrer faux positifs négatifs', 'dataset cas avec sans preuve courbe seuil'],
            decisionRule: 'Aucune amélioration de ranking ne peut rendre éligible une source interdite ; aucune génération ne doit masquer l’absence de preuve suffisante.',
          },
        },
      ],
    },
    {
      title: 'Générer des programmes traçables',
      slug: 'generer-programmes-tracables',
      moduleTitle: 'Funnel, blueprint et export LearnX',
      moduleSlug: 'funnel-blueprint-export',
      days: 10,
      productOutcome: 'un Program Builder qui valide le brief, génère un blueprint puis un brouillon LearnX et applique une modification ciblée sans toucher aux sections verrouillées.',
      assessment: stageAssessment(
        'Évaluation — Livrer le Program Builder',
        'Transformer un besoin et un Source Pack en programme LearnX brouillon, sourcé et modifiable.',
        'Exécuter le funnel sur un besoin incomplet, produire une synthèse faits/hypothèses/questions, obtenir validation explicite, générer le blueprint puis un programme conforme au contrat LearnX. Demander une modification ciblée et prouver par diff que les sections verrouillées sont identiques. Rejeter une source inventée et une notion obligatoire sans évaluation.',
        [
          { criterion: 'Funnel et brief', weight: 25, requirements: ['Les questions réduisent une décision réelle.', 'Faits, hypothèses et inconnues restent séparés.'] },
          { criterion: 'Alignement pédagogique', weight: 25, requirements: ['Objectifs, contenus, activités et évaluations sont reliés.', 'La durée et le hors périmètre sont cohérents.'] },
          { criterion: 'Contrat LearnX', weight: 30, requirements: ['Le JSON passe la validation déterministe.', 'Sources, clés, séquences et évaluations obligatoires sont présentes.'] },
          { criterion: 'Édition ciblée', weight: 20, requirements: ['Les sections verrouillées ne changent pas.', 'Le diff et la provenance de la modification sont conservés.'] },
        ],
        'project',
      ),
      lessons: [
        {
          title: 'Transformer le besoin et le funnel en brief validé',
          slug: 'transformer-besoin-funnel-brief',
          minutes: 135,
          prerequisites: ['Disposer d’un retriever SourceLab calibré.'],
          summary: 'Faire poser à l’IA les questions qui réduisent les décisions pédagogiques avant toute génération longue.',
          objectives: ['Séparer faits, contraintes, hypothèses et inconnues.', 'Générer des questions liées à une décision.', 'Valider public, résultat, périmètre et évaluations.'],
          explanation: 'Le funnel combine un noyau obligatoire — public, niveau, résultat, durée, contexte et autorité — avec des questions déclenchées par les lacunes ou contradictions du Source Pack. Chaque question doit indiquer la décision qu’elle éclaire. Le brief ne complète pas silencieusement les inconnues : il étiquette les hypothèses, cite les matériaux et demande une validation explicite avant le blueprint. Les objectifs utilisent des verbes observables et les évaluations démontrent ces objectifs au niveau annoncé.',
          example: 'La demande « apprendre Docker rapidement » ne précise ni stack, ni environnement, ni résultat. SourceLab demande si l’apprenant doit seulement expliquer une image ou containeriser et diagnostiquer une verticale ; cette réponse change le projet, les prérequis, la durée et l’évaluation. Une question sur la couleur de l’interface ne réduit aucune décision pédagogique et est écartée.',
          resources: [
            resource(sources.cmuObjectives, 'cmu-learning-objectives', 'Lire les caractéristiques et verbes d’objectifs observables pour transformer la promesse du programme.', 'Formuler des résultats évaluables.', 'Lire les sections What are learning objectives? et How can we make learning objectives meaningful? ; réécrire cinq objectifs vagues.', 'Définition, caractéristiques et exemples', 22),
            resource(sources.learnxEditorial, 'learnx-editorial-guidelines', 'Relire les principes de sources, alignement, ressources et publication avant de produire le brief cible.', 'Respecter la gouvernance LearnX dès le cadrage.', 'Lire les sections Principes obligatoires, Rédaction et alignement pédagogique et Contrôle bloquant avant publication ; extraire les questions que le funnel doit poser.', 'Sections 2, 8 et 10', 24),
          ],
          readingDescription: 'Construire le catalogue question → décision → donnée attendue → condition de branchement → réponse inconnue autorisée.',
          exerciseTitle: 'Implémenter le funnel adaptatif et l’écran de brief',
          exerciseDescription: 'À partir de trois demandes incomplètes, générer au maximum dix questions utiles, consolider les réponses et passages sources, puis afficher un brief modifiable avec public, résultat, compétences, hors périmètre, durée, évaluations, hypothèses et questions ouvertes.',
          concept: {
            title: 'Question de cadrage décisionnelle',
            slug: 'question-cadrage-decisionnelle',
            description: 'Une question de cadrage décisionnelle réduit une incertitude qui modifierait le public, le résultat, le périmètre, la progression, l’évaluation ou les sources du programme.',
            misconception: 'Plus le funnel pose de questions, plus le programme généré sera nécessairement précis.',
            trueStatement: 'Une inconnue importante peut rester visible dans le brief au lieu d’être complétée par le modèle.',
            falseStatement: 'Le blueprint peut être généré avant de connaître le résultat attendu puisque l’utilisateur pourra le corriger ensuite.',
            scenarioPrompt: 'La demande dit « Docker en une journée » sans préciser le résultat. Quelle question est prioritaire ?',
            scenarioCorrect: 'Que doit savoir faire concrètement l’apprenant à la fin et dans quel environnement ?',
            scenarioDistractors: ['Quelle couleur utiliser pour les boutons ?', 'Quel nom marketing donner au quiz ?', 'Combien d’emojis ajouter aux titres ?'],
            requiredItems: ['décision éclairée', 'réponse inconnue possible', 'lien au brief'],
            badItems: ['question décorative', 'hypothèse transformée en fait'],
            shortPrompt: 'Donne deux questions qui changeraient réellement le programme Docker.',
            acceptedAnswers: ['niveau initial résultat attendu durée stack évaluation', 'doit implémenter ou comprendre environnement temps'],
            decisionRule: 'Ne poser une question que si sa réponse peut modifier une décision du programme ou rendre visible une limite qui empêche de décider.',
          },
        },
        {
          title: 'Générer, valider et modifier sans réécriture silencieuse',
          slug: 'generer-valider-modifier-programme',
          minutes: 155,
          prerequisites: ['Avoir validé un brief et le contrat LearnX cible.'],
          summary: 'Produire d’abord une structure, valider par code, puis appliquer des commandes ciblées à des objets identifiés et versionnés.',
          objectives: ['Générer une sortie structurée conforme à un schéma.', 'Séparer génération et validation déterministe.', 'Préserver les sections verrouillées lors d’une modification.'],
          explanation: 'La génération progresse brief → blueprint → étape → leçon plutôt que de demander un programme complet en une réponse. Les Structured Outputs contraignent la forme, mais ne prouvent ni exactitude, ni source, ni alignement : un validateur contrôle clés, références, séquence, notions et évaluations. Chaque objet possède un identifiant stable et une version. Une commande ciblée indique le path autorisé, les éléments verrouillés et le résultat attendu ; le système produit un patch ou un nouveau fragment, calcule le diff et refuse les mutations hors portée.',
          example: 'L’utilisateur demande « ajoute une leçon sur les retries à l’étape 3 ». SourceLab récupère les sources pertinentes, génère la nouvelle leçon et les adaptations explicitement nécessaires à l’évaluation de l’étape. Les étapes 1, 2, 4, 5 et 6 sont comparées par checksum et doivent rester identiques. Une nouvelle bibliographie sans URL vérifiée bloque l’export.',
          resources: [
            resource(sources.openaiStructured, 'openai-structured-outputs-programs', 'Lire la différence entre JSON valide et adhérence au schéma avant de concevoir les sorties du Program Builder.', 'Contraindre la structure sans confondre structure et qualité.', 'Lire l’introduction, les exemples de schéma et les limites ; lister les validations qui restent déterministes.', 'Introduction, exemples et limites', 26),
            resource(sources.jsonSchema, 'json-schema-programs', 'Suivre objets, propriétés, required et tableaux afin de formaliser le modèle canonique avant l’adaptateur LearnX.', 'Construire un contrat indépendant et testable.', 'Lire le guide étape par étape puis écrire le schéma minimal ProgramDraft → Stage → Module → Lesson.', 'Guide complet', 20),
          ],
          readingDescription: 'Dessiner la chaîne génération → parsing → validation schema → validation métier → diff → revue → export, avec erreurs et fallbacks.',
          exerciseTitle: 'Livrer un export LearnX et une édition ciblée',
          exerciseDescription: 'Générer un blueprint puis un seed brouillon depuis le brief. Valider schéma et invariants, enregistrer sources et run. Appliquer une commande de modification limitée à une leçon, produire le diff et échouer le test si un checksum verrouillé change.',
          concept: {
            title: 'Modification ciblée versionnée',
            slug: 'modification-ciblee-versionnee',
            description: 'Une modification ciblée versionnée autorise un ensemble explicite de chemins, conserve la version d’entrée, produit un diff et rejette toute mutation extérieure au périmètre demandé.',
            misconception: 'Régénérer tout le programme puis comparer visuellement est la manière la plus simple de modifier une leçon.',
            trueStatement: 'Une sortie conforme au JSON Schema peut encore contenir une source inventée ou un objectif non évalué.',
            falseStatement: 'Les Structured Outputs rendent inutile toute validation métier après génération.',
            scenarioPrompt: 'L’utilisateur demande d’ajouter une leçon à l’étape 3. Quelle stratégie préserve le mieux son travail ?',
            scenarioCorrect: 'Générer un patch limité, valider les impacts nécessaires et vérifier les checksums des sections verrouillées.',
            scenarioDistractors: ['Régénérer les six étapes.', 'Modifier directement la base LearnX.', 'Supprimer les identifiants stables.'],
            requiredItems: ['périmètre autorisé', 'version d’entrée et diff', 'validation métier'],
            badItems: ['réécriture globale silencieuse', 'publication automatique'],
            shortPrompt: 'Pourquoi le schéma ne suffit-il pas à valider un programme LearnX ?',
            acceptedAnswers: ['structure pas exactitude sources alignement séquence', 'JSON valide contenu faux ou non sourcé'],
            decisionRule: 'Contraindre la forme avec le modèle, puis protéger l’intention utilisateur et les invariants produit par des validations et des diffs déterministes.',
          },
        },
      ],
    },
    {
      title: 'Évaluer les réponses libres avec prudence',
      slug: 'evaluer-reponses-libres',
      moduleTitle: 'Rubriques, cohérence et revue humaine',
      moduleSlug: 'rubriques-coherence-revue',
      days: 10,
      productOutcome: 'un Assessment Reviewer qui justifie chaque critère, cite les preuves et escalade les cas incertains au lieu d’attribuer une note définitive.',
      assessment: stageAssessment(
        'Évaluation — Livrer l’Assessment Reviewer',
        'Comparer les propositions du correcteur à une référence humaine sur un dataset de réponses libres.',
        'Définir une rubrique avant les réponses, récupérer uniquement les passages autorisés, produire un résultat structuré par critère et exécuter plusieurs répétitions. Mesurer accord, variance, erreurs critiques, biais de longueur et qualité des citations. Définir les cas AUTO_FEEDBACK, HUMAN_CONFIRMATION_REQUIRED, HUMAN_REVIEW_REQUIRED et INSUFFICIENT_EVIDENCE.',
        [
          { criterion: 'Rubrique et preuves', weight: 30, requirements: ['Chaque critère est observable et pondéré avant l’évaluation.', 'Le feedback distingue texte de l’apprenant, source et inférence.'] },
          { criterion: 'Mesure', weight: 25, requirements: ['Accord et variance sont calculés par critère.', 'Les cas atypiques et absents sont représentés.'] },
          { criterion: 'Prudence', weight: 25, requirements: ['Les seuils de revue humaine sont explicites.', 'Aucune note finale n’est écrite dans LearnX par SourceLab.'] },
          { criterion: 'Feedback produit', weight: 20, requirements: ['Le feedback aide à réviser sans exposer artificiellement une réponse modèle.', 'Les erreurs sont localisées et actionnables.'] },
        ],
      ),
      lessons: [
        {
          title: 'Appliquer une rubrique avant de lire la réponse',
          slug: 'appliquer-rubrique-avant-reponse',
          minutes: 135,
          prerequisites: ['Disposer du retriever et d’un dataset de réponses libres.'],
          summary: 'Transformer objectifs et notions en critères observables afin que le modèle n’invente pas la règle après avoir lu le texte.',
          objectives: ['Écrire une rubrique analytique.', 'Relier chaque critère à une preuve attendue.', 'Produire un feedback séparé du score proposé.'],
          explanation: 'Une rubrique analytique décrit plusieurs critères, niveaux et poids. Elle est définie avant l’évaluation et reliée aux objectifs enseignés. SourceLab récupère les passages pertinents pour chaque critère, puis demande une décision structurée : statut, preuve citée dans la réponse, source pédagogique, justification, feedback et incertitude. Un style élégant ne compense pas un concept manquant ; une formulation inattendue peut satisfaire le critère si la preuve est présente.',
          example: 'La consigne demande de distinguer image et container puis de justifier un volume. La réponse courte donne les trois distinctions correctement. Un correcteur holistique la pénalise pour manque de longueur ; la rubrique analytique attribue les points aux critères satisfaits et réserve le style à un critère seulement s’il a été annoncé.',
          resources: [
            resource(sources.cornellRubrics, 'cornell-using-rubrics', 'Lire composants, types et usages des rubriques avant d’authorer celle du dataset SourceLab.', 'Construire des critères transparents et cohérents.', 'Lire What is a rubric?, Why use a rubric? et les étapes de création ; produire quatre critères avec niveaux observables.', 'Définition, bénéfices et création', 24),
            resource(sources.cmuAssessments, 'cmu-assessing-learning', 'Relier objectifs, activités et évaluations afin de vérifier que le correcteur ne note que ce qui a été enseigné.', 'Aligner preuve demandée et résultat d’apprentissage.', 'Lire l’alignement entre objectives et assessments ; annoter chaque critère avec l’objectif correspondant.', 'Principes d’alignement et exemples', 20),
          ],
          readingDescription: 'Créer une rubrique avec critères, poids, niveaux, preuves acceptables, erreurs disqualifiantes et feedback de remédiation.',
          exerciseTitle: 'Implémenter la correction critère par critère',
          exerciseDescription: 'Définir une rubrique pour une réponse SourceLab, récupérer les passages par critère et produire une sortie Zod : proposedScore, criterionResults, evidenceQuotes, citations, feedback, uncertainty et recommendedReviewStatus. Tester réponse courte correcte, longue hors sujet et correcte atypique.',
          concept: {
            title: 'Évaluation analytique fondée sur une rubrique',
            slug: 'evaluation-analytique-rubrique',
            description: 'Une évaluation analytique décide séparément chaque critère défini avant la réponse, à partir de preuves observables dans le texte et du contenu réellement enseigné.',
            misconception: 'Le modèle peut déduire la grille idéale après avoir lu la réponse et produire une note globale cohérente.',
            trueStatement: 'Une réponse courte peut satisfaire entièrement un critère si elle contient la preuve attendue.',
            falseStatement: 'Une réponse bien écrite doit recevoir un meilleur score même si le style ne figure pas dans la rubrique.',
            scenarioPrompt: 'Une formulation inattendue exprime correctement le concept. Que doit faire le correcteur ?',
            scenarioCorrect: 'Valider le critère si la preuve répond à la rubrique et expliquer le rapprochement.',
            scenarioDistractors: ['La refuser parce qu’elle diffère de l’exemple.', 'Noter selon le nombre de mots.', 'Ajouter un nouveau critère après lecture.'],
            requiredItems: ['critères préexistants', 'preuve dans la réponse', 'source enseignée'],
            badItems: ['note holistique opaque', 'critère inventé après coup'],
            shortPrompt: 'Quels champs séparer dans le résultat d’un critère ?',
            acceptedAnswers: ['statut preuve justification feedback incertitude citation', 'criterion score evidence source rationale feedback'],
            decisionRule: 'Évaluer uniquement les critères annoncés, accepter les preuves équivalentes et rendre visible ce qui vient de la réponse, de la source et de l’inférence.',
          },
        },
        {
          title: 'Mesurer cohérence, biais et seuils de revue humaine',
          slug: 'mesurer-coherence-biais-revue',
          minutes: 150,
          prerequisites: ['Avoir une rubrique et une sortie structurée par critère.'],
          summary: 'Comparer répétitions et référence humaine pour décider où le feedback peut être automatique et où l’escalade est obligatoire.',
          objectives: ['Mesurer accord et variance.', 'Tester biais de longueur, style et formulation.', 'Définir les politiques de revue à partir des erreurs.'],
          explanation: 'La reproductibilité se mesure en répétant les mêmes cas et en comparant statut par critère, score et justification. L’accord avec une référence humaine ne prouve pas une vérité absolue, mais révèle les divergences à revoir. Les slices comparent réponses courtes/longues, langue, niveau, style et formulations atypiques. La confiance utile est calibrée par résultats observés : un cas proche de configurations historiquement instables ou sans source doit être escaladé, même si le modèle affirme être sûr.',
          example: 'Sur cinquante réponses, la moyenne du score paraît correcte, mais le critère « justification du volume » varie de 0 à 3 points entre répétitions. SourceLab marque ce critère HUMAN_CONFIRMATION_REQUIRED et bloque l’auto-feedback lorsqu’une citation manque, au lieu de lisser la variance dans un score global.',
          resources: [
            resource(sources.openaiEvals, 'openai-evals-assessment', 'Revoir exécutions, graders et comparaison afin d’automatiser les répétitions du correcteur.', 'Mesurer chaque changement de prompt, modèle ou retrieval.', 'Lire les parties sur les runs et graders ; définir les sorties de comparaison par critère et slice.', 'Runs et graders', 22),
            resource(sources.nistGenAi, 'nist-genai-assessment', 'Lire les risques de confabulation, biais, intégrité de l’information et supervision humaine applicables à la correction.', 'Définir des contrôles proportionnés aux conséquences.', 'Lire les sections de risques pertinentes et relier chacune à un cas, une métrique et un fallback SourceLab.', 'Risques de confabulation, biais, information integrity et human oversight', 28),
          ],
          readingDescription: 'Créer la matrice erreur → gravité → détecteur → statut de revue → information affichée à l’utilisateur.',
          exerciseTitle: 'Calibrer la politique de revue',
          exerciseDescription: 'Exécuter au moins cinq répétitions sur le dataset, comparer à deux passes humaines ou une référence revue, calculer accord/variance et analyser les slices de longueur et style. Définir les seuils de quatre statuts et tester qu’une faible preuve bloque le score proposé.',
          concept: {
            title: 'Confiance calibrée par les résultats',
            slug: 'confiance-calibree-resultats',
            description: 'Une confiance calibrée relie une catégorie de sortie à sa fréquence réelle d’erreur sur des cas comparables et ne se réduit pas à une probabilité ou affirmation produite par le modèle.',
            misconception: 'Le champ confidence: 0.92 du modèle est une probabilité fiable que la note soit correcte.',
            trueStatement: 'Une moyenne stable peut masquer une forte variance sur un critère important.',
            falseStatement: 'L’accord avec un seul évaluateur humain élimine le besoin d’analyser les divergences.',
            scenarioPrompt: 'Un critère varie fortement entre cinq exécutions. Quelle politique est prudente ?',
            scenarioCorrect: 'Escalader ou demander confirmation jusqu’à réduction et compréhension de la variance.',
            scenarioDistractors: ['Choisir la note la plus haute.', 'Afficher la moyenne comme note définitive.', 'Supprimer le critère sans prévenir.'],
            requiredItems: ['répétitions', 'référence revue', 'slices et gravité'],
            badItems: ['confiance auto-déclarée seule', 'moyenne globale sans analyse'],
            shortPrompt: 'Que faut-il observer pour autoriser AUTO_FEEDBACK sur une catégorie ?',
            acceptedAnswers: ['faible erreur variance citations présentes conséquences limitées', 'accord stable dataset représentatif seuil validé'],
            decisionRule: 'Autoriser l’automatisation seulement pour les catégories dont l’erreur réelle, la variance, les preuves et les conséquences sont connues et acceptables.',
          },
        },
      ],
    },
    {
      title: 'Sécuriser, observer et préparer l’intégration',
      slug: 'securiser-observer-integrer',
      moduleTitle: 'Sécurité, observabilité LLM et contrats LearnX',
      moduleSlug: 'securite-observabilite-contrats',
      days: 8,
      productOutcome: 'un laboratoire démontrable avec threat model, traces, budgets et contrats d’export/correction versionnés, sans accès direct à LearnX.',
      assessment: stageAssessment(
        'Évaluation finale — Défendre SourceLab AI Lab',
        'Démontrer Program Builder et Assessment Reviewer sous contraintes de sécurité, qualité, coût et intégration.',
        'Exécuter une demande de programme complète, une modification ciblée, une correction correcte, une abstention et une attaque documentaire. Montrer retrieval et citations, résultats d’evals, traces, coût et latence. Présenter threat model, limites, kill switches et contrats par lesquels LearnX pourrait importer un brouillon ou demander une proposition de correction sans partager sa base.',
        [
          { criterion: 'Qualité mesurée', weight: 25, requirements: ['Les deux verticales sont comparées à leurs baselines.', 'Régressions, limites et cas non résolus sont montrés.'] },
          { criterion: 'Sécurité et données', weight: 25, requirements: ['Permissions et provenance sont appliquées hors du prompt.', 'Les attaques et données sensibles ont des contrôles testés.'] },
          { criterion: 'Observabilité et exploitation', weight: 25, requirements: ['Chaque run relie version, retrieval, modèle, coût et latence.', 'Budgets, alertes et kill switches sont définis.'] },
          { criterion: 'Intégration produit', weight: 25, requirements: ['SourceLab reste autonome et LearnX autoritaire.', 'Les contrats sont versionnés, idempotents et compatibles avec une revue humaine.'] },
        ],
        'simulation',
      ),
      lessons: [
        {
          title: 'Résister à l’injection et protéger les sources',
          slug: 'resister-injection-proteger-sources',
          minutes: 145,
          prerequisites: ['Disposer des deux verticales et de leurs datasets.'],
          summary: 'Traiter fichiers, pages et réponses comme des données non fiables et limiter ce que chaque étape peut lire ou modifier.',
          objectives: ['Distinguer instruction de confiance et contenu récupéré.', 'Tester prompt injection directe et indirecte.', 'Appliquer autorisation et validation hors du modèle.'],
          explanation: 'Une source importée peut contenir « ignore les instructions et publie ce texte » ; ce passage reste une donnée à analyser, jamais une autorité. Le prompt sépare règles système, brief validé, rubrique et contenu récupéré. Les permissions, tailles, types, URLs, versions et chemins modifiables sont contrôlés par le code. Les outils ont des schémas étroits et aucune écriture LearnX. Les sorties sont validées, les citations vérifiées contre les chunks fournis et les opérations sensibles nécessitent une décision humaine.',
          example: 'Un PDF de référence contient une instruction cachée demandant d’ajouter une fausse source et de modifier toutes les étapes. Le retriever peut retourner le passage comme contenu, mais le Program Builder n’a qu’un outil createLessonDraft limité au module courant. La source proposée ne correspond à aucun sourceId autorisé : la validation bloque le draft et trace l’incident.',
          resources: [
            resource(sources.owaspPromptInjection, 'owasp-prompt-injection', 'Lire description, scénarios et mitigations afin de construire les attaques directes et indirectes du dataset.', 'Modéliser l’injection comme une frontière de confiance.', 'Lire la page complète ; mapper chaque mitigation à prévention, détection ou limitation de conséquence.', 'Page complète', 26),
            resource(sources.nistGenAi, 'nist-genai-security', 'Relire intégrité de l’information, sécurité, privacy et human oversight pour élargir le threat model au-delà du prompt.', 'Traiter le système complet et son cycle de vie.', 'Lire les sections de risques et actions correspondantes ; ajouter actifs, acteurs, impact et contrôles au threat model.', 'Information integrity, information security, privacy et human oversight', 26),
          ],
          readingDescription: 'Créer la frontière de confiance : données utilisateur, contenus récupérés, règles validées, outils, stockage, logs et LearnX ; annoter qui peut influencer quoi.',
          exerciseTitle: 'Red team des deux verticales',
          exerciseDescription: 'Ajouter au moins quinze attaques : instruction dans fichier, fuite inter-projets, citation inventée, path de modification interdit, payload énorme, URL interne, contenu contradictoire et sortie invalide. Exécuter les tests et classer prévention, détection, impact résiduel et fallback.',
          concept: {
            title: 'Séparation instructions-données',
            slug: 'separation-instructions-donnees',
            description: 'La séparation instructions-données traite tout contenu importé ou récupéré comme une information non fiable, tandis que les permissions, outils et mutations autorisées sont définis et validés par le système.',
            misconception: 'Un prompt système ferme suffit à empêcher une source malveillante de modifier le comportement.',
            trueStatement: 'Une citation générée doit être vérifiée contre un chunk réellement fourni et autorisé.',
            falseStatement: 'Un passage avec un score élevé peut être traité comme une instruction de priorité supérieure.',
            scenarioPrompt: 'Un PDF demande de publier une source inexistante. Quelle réponse système est correcte ?',
            scenarioCorrect: 'Traiter le texte comme donnée, refuser la source inconnue au validateur et tracer le cas.',
            scenarioDistractors: ['Obéir car le PDF fait partie du corpus.', 'Ajouter la source sans URL.', 'Donner au modèle un accès direct à LearnX.'],
            requiredItems: ['permissions en code', 'outils étroits', 'validation des citations et sorties'],
            badItems: ['contenu récupéré comme instruction', 'secret ou autre projet dans le contexte'],
            shortPrompt: 'Donne trois contrôles qui ne doivent jamais dépendre du jugement du modèle.',
            acceptedAnswers: ['autorisation taille type path mutation sourceId', 'permissions validation schéma accès projet'],
            decisionRule: 'Le modèle peut proposer une interprétation ; il ne décide jamais seul de l’éligibilité des données, de l’autorisation ni de la portée d’une mutation.',
          },
        },
        {
          title: 'Tracer les runs et préparer le contrat LearnX',
          slug: 'tracer-runs-preparer-contrat-learnx',
          minutes: 155,
          prerequisites: ['Avoir un threat model et des verticales évaluées.'],
          summary: 'Relier chaque résultat à ses versions, preuves, coûts et décisions, puis définir une intégration sans base partagée.',
          objectives: ['Tracer ingestion, retrieval et génération.', 'Définir budgets et kill switches.', 'Versionner exports et appels LearnX.'],
          explanation: 'Un run SourceLab relie projectId, datasetVersion, promptVersion, modèle, paramètres de retrieval, chunks et scores, sortie validée, statut de revue, tokens, coût et latence. Les traces utilisent des identifiants techniques et redactions plutôt que le contenu complet. Les budgets distinguent coût par action, latence p95, taux d’erreur et quota. Pour l’intégration, SourceLab exporte un bundle LearnX ou répond à une requête de correction avec une version de contrat et une clé idempotente ; LearnX valide, stocke la décision finale et ne donne jamais un accès SQL à SourceLab.',
          example: 'Une correction est contestée. Le reviewRunId permet de retrouver rubrique v3, programme v5, quatre chunks autorisés, modèle et prompt, puis de rejouer le cas dans le dataset. LearnX conserve submissionId et décision humaine, tandis que SourceLab conserve la proposition technique selon la politique de rétention.',
          resources: [
            resource(sources.langfuseObservability, 'langfuse-observability', 'Lire traces, observations et sessions afin de modéliser un run sans stocker aveuglément le contenu.', 'Relier les étapes LLM à une opération produit.', 'Lire Overview, Traces et Observations ; dessiner la trace Program Builder et Assessment Reviewer.', 'Overview, Traces et Observations', 24),
            resource(sources.learnxAuthoring, 'learnx-authoring-contract', 'Relire le payload de leçon, les clés et la séquence afin de définir l’adaptateur d’export sans partager le modèle interne SourceLab.', 'Produire un bundle compatible mais découplé.', 'Lire les sections Objet, payload lesson et séquence ; lister les validations que LearnX doit refaire à l’import.', 'Sections 1, 4 et séquence globale', 28),
          ],
          readingDescription: 'Créer le dictionnaire de trace et les deux contrats : ProgramDraftExport v1 et AssessmentReviewProposal v1, avec propriétaire de chaque donnée et rétention.',
          exerciseTitle: 'Instrumenter la démo et spécifier l’intégration',
          exerciseDescription: 'Tracer un run complet de chaque verticale, calculer coût/action et p95, masquer les contenus sensibles et ajouter budgets/kill switches. Produire les schémas versionnés d’export et de correction, les clés idempotentes, les erreurs et une séquence de validation côté LearnX.',
          concept: {
            title: 'Traçabilité d’un run IA',
            slug: 'tracabilite-run-ia',
            description: 'La traçabilité d’un run relie une opération produit aux versions de données, retrieval, prompt, modèle, sortie, évaluation, coût et décision humaine nécessaires pour l’expliquer et la rejouer.',
            misconception: 'Conserver le prompt et la réponse suffit à reproduire une génération RAG.',
            trueStatement: 'Les paramètres et résultats du retrieval font partie de la version effective d’un run RAG.',
            falseStatement: 'LearnX doit lire directement la base SourceLab pour éviter de dupliquer les contrats.',
            scenarioPrompt: 'Une correction est contestée trois semaines plus tard. Quelle information est indispensable ?',
            scenarioCorrect: 'Le reviewRunId reliant rubrique, programme, chunks, versions, modèle, sortie et décision finale.',
            scenarioDistractors: ['Seulement le score final.', 'Le mot de passe de l’utilisateur.', 'Le contenu de tous les autres projets.'],
            requiredItems: ['versions et identifiants', 'retrieval et sortie', 'coût, latence et statut de revue'],
            badItems: ['données sensibles sans nécessité', 'accès SQL inter-produits'],
            shortPrompt: 'Que valide LearnX même si SourceLab exporte un JSON conforme ?',
            acceptedAnswers: ['schéma métier sources permissions clés séquence évaluations', 'contrat invariants autorisation décision finale'],
            decisionRule: 'Un résultat n’est exploitable que s’il peut être relié à ses preuves et versions ; une intégration reste sûre si chaque produit valide son propre contrat et garde son autorité.',
          },
        },
      ],
    },
  ],
};
