const sources = {
  nodeProcess: {
    type: 'website',
    title: 'Process — Node.js documentation',
    author: 'Node.js',
    url: 'https://nodejs.org/api/process.html',
    citation: 'Node.js. (s. d.). Process. Node.js documentation. Consulté le 18 août 2026.',
  },
  nodeEnv: {
    type: 'website',
    title: 'Environment Variables — Node.js documentation',
    author: 'Node.js',
    url: 'https://nodejs.org/api/environment_variables.html',
    citation: 'Node.js. (s. d.). Environment Variables. Node.js documentation. Consulté le 18 août 2026.',
  },
  mdnHttp: {
    type: 'article',
    title: 'An overview of HTTP',
    author: 'MDN Web Docs',
    url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/Overview',
    citation: 'MDN Web Docs. (s. d.). An overview of HTTP. Consulté le 18 août 2026.',
  },
  mdnStatus: {
    type: 'article',
    title: 'HTTP response status codes',
    author: 'MDN Web Docs',
    url: 'https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status',
    citation: 'MDN Web Docs. (s. d.). HTTP response status codes. Consulté le 18 août 2026.',
  },
  twelveConfig: {
    type: 'article',
    title: 'The Twelve-Factor App — Config',
    author: 'Adam Wiggins',
    url: 'https://12factor.net/config',
    citation: 'Wiggins, A. (2017). The Twelve-Factor App: Config.',
  },
  twelveDisposability: {
    type: 'article',
    title: 'The Twelve-Factor App — Disposability',
    author: 'Adam Wiggins',
    url: 'https://12factor.net/disposability',
    citation: 'Wiggins, A. (2017). The Twelve-Factor App: Disposability.',
  },
  dockerConcepts: {
    type: 'website',
    title: 'What is a container?',
    author: 'Docker',
    url: 'https://docs.docker.com/get-started/docker-concepts/the-basics/what-is-a-container/',
    citation: 'Docker. (s. d.). What is a container? Docker Docs. Consulté le 18 août 2026.',
  },
  dockerBestPractices: {
    type: 'website',
    title: 'Building best practices',
    author: 'Docker',
    url: 'https://docs.docker.com/build/building/best-practices/',
    citation: 'Docker. (s. d.). Building best practices. Docker Docs. Consulté le 18 août 2026.',
  },
  dockerMultiStage: {
    type: 'website',
    title: 'Multi-stage builds',
    author: 'Docker',
    url: 'https://docs.docker.com/build/building/multi-stage/',
    citation: 'Docker. (s. d.). Multi-stage builds. Docker Docs. Consulté le 18 août 2026.',
  },
  composeStartup: {
    type: 'website',
    title: 'Control startup and shutdown order in Compose',
    author: 'Docker',
    url: 'https://docs.docker.com/compose/how-tos/startup-order/',
    citation: 'Docker. (s. d.). Control startup and shutdown order in Compose. Docker Docs. Consulté le 18 août 2026.',
  },
  composeNetworking: {
    type: 'website',
    title: 'Networking in Compose',
    author: 'Docker',
    url: 'https://docs.docker.com/compose/how-tos/networking/',
    citation: 'Docker. (s. d.). Networking in Compose. Docker Docs. Consulté le 18 août 2026.',
  },
  dockerVolumes: {
    type: 'website',
    title: 'Volumes',
    author: 'Docker',
    url: 'https://docs.docker.com/engine/storage/volumes/',
    citation: 'Docker. (s. d.). Volumes. Docker Docs. Consulté le 18 août 2026.',
  },
  hono: {
    type: 'website',
    title: 'Hono documentation',
    author: 'Hono',
    url: 'https://hono.dev/docs/',
    citation: 'Hono. (s. d.). Hono documentation. Consulté le 18 août 2026.',
  },
  honoValidation: {
    type: 'website',
    title: 'Validation — Hono guides',
    author: 'Hono',
    url: 'https://hono.dev/docs/guides/validation',
    citation: 'Hono. (s. d.). Validation. Hono documentation. Consulté le 18 août 2026.',
  },
  awsIdempotency: {
    type: 'article',
    title: 'Making retries safe with idempotent APIs',
    author: 'Amazon Web Services',
    url: 'https://aws.amazon.com/builders-library/making-retries-safe-with-idempotent-APIs/',
    citation: 'Amazon Web Services. (s. d.). Making retries safe with idempotent APIs. Builders’ Library. Consulté le 18 août 2026.',
  },
  postgresTransactions: {
    type: 'website',
    title: 'Transactions',
    author: 'PostgreSQL Global Development Group',
    url: 'https://www.postgresql.org/docs/current/tutorial-transactions.html',
    citation: 'PostgreSQL Global Development Group. (2026). Transactions. PostgreSQL documentation.',
  },
  postgresConstraints: {
    type: 'website',
    title: 'Constraints',
    author: 'PostgreSQL Global Development Group',
    url: 'https://www.postgresql.org/docs/current/ddl-constraints.html',
    citation: 'PostgreSQL Global Development Group. (2026). Constraints. PostgreSQL documentation.',
  },
  postgresIndexes: {
    type: 'website',
    title: 'Indexes',
    author: 'PostgreSQL Global Development Group',
    url: 'https://www.postgresql.org/docs/current/indexes.html',
    citation: 'PostgreSQL Global Development Group. (2026). Indexes. PostgreSQL documentation.',
  },
  postgresExplain: {
    type: 'website',
    title: 'Using EXPLAIN',
    author: 'PostgreSQL Global Development Group',
    url: 'https://www.postgresql.org/docs/current/using-explain.html',
    citation: 'PostgreSQL Global Development Group. (2026). Using EXPLAIN. PostgreSQL documentation.',
  },
  prismaMigrate: {
    type: 'website',
    title: 'Development and production — Prisma Migrate',
    author: 'Prisma',
    url: 'https://www.prisma.io/docs/orm/prisma-migrate/workflows/development-and-production',
    citation: 'Prisma. (s. d.). Development and production. Prisma Migrate documentation. Consulté le 18 août 2026.',
  },
  prismaTransactions: {
    type: 'website',
    title: 'Transactions and batch queries',
    author: 'Prisma',
    url: 'https://www.prisma.io/docs/orm/prisma-client/queries/transactions',
    citation: 'Prisma. (s. d.). Transactions and batch queries. Prisma Client documentation. Consulté le 18 août 2026.',
  },
  testcontainers: {
    type: 'website',
    title: 'Testcontainers for Node.js — Quickstart',
    author: 'Testcontainers',
    url: 'https://node.testcontainers.org/quickstart/',
    citation: 'Testcontainers. (s. d.). Testcontainers for Node.js: Quickstart. Consulté le 18 août 2026.',
  },
  playwrightApi: {
    type: 'website',
    title: 'API testing',
    author: 'Microsoft Playwright',
    url: 'https://playwright.dev/docs/api-testing',
    citation: 'Microsoft. (s. d.). API testing. Playwright documentation. Consulté le 18 août 2026.',
  },
  githubWorkflows: {
    type: 'website',
    title: 'About workflows',
    author: 'GitHub',
    url: 'https://docs.github.com/en/actions/writing-workflows/about-workflows',
    citation: 'GitHub. (s. d.). About workflows. GitHub Actions documentation. Consulté le 18 août 2026.',
  },
  githubArtifacts: {
    type: 'website',
    title: 'Store and share data with workflow artifacts',
    author: 'GitHub',
    url: 'https://docs.github.com/en/actions/tutorials/store-and-share-data',
    citation: 'GitHub. (s. d.). Store and share data with workflow artifacts. GitHub Actions documentation. Consulté le 18 août 2026.',
  },
  githubEnvironments: {
    type: 'website',
    title: 'Deployments and environments',
    author: 'GitHub',
    url: 'https://docs.github.com/en/actions/reference/deployments-and-environments',
    citation: 'GitHub. (s. d.). Deployments and environments. GitHub Actions documentation. Consulté le 18 août 2026.',
  },
  otelPrimer: {
    type: 'website',
    title: 'Observability primer',
    author: 'OpenTelemetry',
    url: 'https://opentelemetry.io/docs/concepts/observability-primer/',
    citation: 'OpenTelemetry. (s. d.). Observability primer. Consulté le 18 août 2026.',
  },
  googleMonitoring: {
    type: 'book_chapter',
    title: 'Monitoring Distributed Systems',
    author: 'Google',
    url: 'https://sre.google/sre-book/monitoring-distributed-systems/',
    citation: 'Beyer, B., Jones, C., Petoff, J., & Murphy, N. R. (dir.). (2016). Monitoring Distributed Systems. Site Reliability Engineering. O’Reilly / Google.',
  },
  googlePostmortem: {
    type: 'book_chapter',
    title: 'Postmortem Culture: Learning from Failure',
    author: 'Google',
    url: 'https://sre.google/sre-book/postmortem-culture/',
    citation: 'Beyer, B., Jones, C., Petoff, J., & Murphy, N. R. (dir.). (2016). Postmortem Culture: Learning from Failure. Site Reliability Engineering. O’Reilly / Google.',
  },
  owaspLogging: {
    type: 'article',
    title: 'Logging Cheat Sheet',
    author: 'OWASP Foundation',
    url: 'https://cheatsheetseries.owasp.org/cheatsheets/Logging_Cheat_Sheet.html',
    citation: 'OWASP Foundation. (s. d.). Logging Cheat Sheet. OWASP Cheat Sheet Series. Consulté le 18 août 2026.',
  },
};

function resource(source, key, description, objective, instructions, scope, minutes = 15, isRequired = true) {
  return { ...source, key, description, objective, instructions, scope, minutes, isRequired };
}

function stageAssessment(title, description, instructions, criteria, type = 'practical_exercise') {
  return {
    title,
    type,
    isRequired: true,
    passingScore: 75,
    description,
    instructions,
    rubric: criteria,
  };
}

export const infraDefinition = {
  title: 'SourceLab — Socle d’ingénierie en production',
  slug: 'sourcelab-ingenierie-production',
  seedFile: 'sourcelab-production-engineering-program.json',
  position: 5,
  estimatedDurationDays: 42,
  audience: 'Développeur front-end expérimenté maîtrisant TypeScript et souhaitant posséder une verticale jusqu’à la production sans devenir DevOps.',
  description: 'Parcours pratique de six semaines pour construire la V1 autonome de SourceLab : un espace qui importe, traite, classe, versionne et exporte des sources pédagogiques. Le programme renforce runtime, HTTP, Docker, API, workers, PostgreSQL, tests d’intégration, CI/CD, observabilité et réponse aux incidents, sans viser l’administration d’une plateforme complexe.',
  productPromise: 'À la fin du parcours, SourceLab permet de créer un projet, importer des matériaux, suivre leur traitement, corriger leurs métadonnées, détecter les doublons et exporter un Source Pack traçable. La valeur utilisateur existe avant toute fonctionnalité générative.',
  cumulativeDeliverable: 'Un dépôt SourceLab autonome contenant une interface minimale, une API Hono, un worker, PostgreSQL, un stockage de fichiers, des images Docker, un environnement Compose, des tests d’intégration, une CI, un déploiement de démonstration, des logs structurés et un runbook. Il prépare sans l’implémenter encore le pipeline RAG du second programme.',
  finality: 'Faire passer l’apprenant d’une maîtrise principalement front-end à la capacité de construire, intégrer, livrer et diagnostiquer un petit service de production. Chaque notion est appliquée à une capacité produit visible de SourceLab plutôt qu’à une infrastructure abstraite.',
  startingProfile: 'L’apprenant sait développer avec TypeScript, comprendre une API et manipuler Git. Il peut utiliser un terminal, mais ne maîtrise pas encore systématiquement processus, réseau, containers, workers, migrations, CI/CD ou diagnostic de production.',
  learningOutcomes: [
    'suivre une requête depuis l’interface SourceLab jusqu’au processus et à PostgreSQL ;',
    'construire des images Docker reproductibles et orchestrer localement plusieurs services ;',
    'concevoir un contrat d’import et un traitement asynchrone idempotent ;',
    'faire évoluer les données avec migrations, contraintes et mesures avant optimisation ;',
    'tester une verticale avec de vraies dépendances et automatiser sa livraison ;',
    'observer le service, limiter un incident et choisir un roll-forward ou un rollback argumenté.',
  ],
  outOfScope: [
    'administrer Kubernetes, un service mesh ou une plateforme multi-région ;',
    'devenir SRE ou ingénieur cloud spécialisé ;',
    'implémenter le RAG, les embeddings ou la correction IA dans ce premier programme ;',
    'partager la base de données ou le dépôt de LearnX.',
  ],
  stages: [
    {
      title: 'Comprendre l’exécution et diagnostiquer',
      slug: 'diagnostiquer-execution',
      moduleTitle: 'Runtime, HTTP et configuration',
      moduleSlug: 'runtime-http-configuration',
      days: 7,
      productOutcome: 'une carte de requête SourceLab et un diagnostic reproductible sur un environnement volontairement cassé.',
      assessment: stageAssessment(
        'Évaluation — Diagnostiquer le squelette SourceLab',
        'Réparer un squelette SourceLab dont l’interface ne parvient plus à obtenir le statut d’un import.',
        'Démarrer l’environnement fourni, reproduire le symptôme, formuler au moins trois hypothèses ordonnées, collecter des preuves avec les outils adaptés, identifier la frontière en échec, appliquer un correctif minimal puis documenter la vérification. Livrer une carte de la requête et un journal symptôme → hypothèse → test → résultat → décision.',
        [
          { criterion: 'Carte d’exécution', weight: 25, requirements: ['Les frontières navigateur, HTTP, processus, dépendance et réponse sont explicites.', 'Les ports, variables et identifiants utiles sont indiqués.'] },
          { criterion: 'Méthode de diagnostic', weight: 30, requirements: ['Les hypothèses sont testables et ordonnées.', 'Une seule variable est modifiée à la fois.'] },
          { criterion: 'Correction et vérification', weight: 30, requirements: ['La cause est distinguée du symptôme.', 'Le correctif minimal est vérifié par un test reproductible.'] },
          { criterion: 'Communication', weight: 15, requirements: ['Le journal permet à un tiers de reproduire le raisonnement.', 'Les inconnues restantes ne sont pas masquées.'] },
        ],
      ),
      lessons: [
        {
          title: 'Suivre une requête jusqu’au processus',
          slug: 'suivre-requete-jusqu-au-processus',
          minutes: 95,
          summary: 'Comprendre le trajet d’une action utilisateur à travers HTTP, le processus serveur et ses dépendances afin de localiser une panne sans deviner.',
          objectives: ['Cartographier les frontières traversées par une requête SourceLab.', 'Distinguer build, démarrage et runtime.', 'Associer un symptôme à la première preuve à collecter.'],
          explanation: 'Une action « Importer une source » déclenche plusieurs contrats successifs : résolution de l’origine, connexion HTTP, routage Hono, validation, logique métier, accès au stockage ou à PostgreSQL, puis sérialisation de la réponse. Le processus Node possède un environnement, un répertoire de travail, des entrées-sorties et un code de sortie. Un diagnostic fiable observe ces frontières dans l’ordre au lieu d’attribuer immédiatement la panne à la couche la plus familière.',
          example: 'Dans SourceLab, le bouton d’import reste en chargement. La console du navigateur montre un timeout, mais un appel curl direct à l’API locale répond 201. Cette preuve ne disculpe pas tout le backend : elle déplace d’abord l’enquête vers l’URL utilisée par le client, le réseau entre les deux processus et les différences de configuration au runtime.',
          resources: [
            resource(sources.nodeProcess, 'node-process-runtime', 'Lire les sections sur les informations du processus, les codes de sortie et les signaux afin d’identifier ce qui est observable au runtime.', 'Relier un service Node à son processus réel.', 'Lire les sections Process events, Exit codes et Signal events ; noter quatre informations utiles au diagnostic.', 'Process events, Exit codes et Signal events', 18),
            resource(sources.mdnHttp, 'mdn-http-overview', 'Revoir le modèle client-serveur, les messages HTTP et les intermédiaires avant de dessiner le trajet d’une requête SourceLab.', 'Cartographier une requête HTTP de bout en bout.', 'Lire les parties Components of HTTP-based systems et Basic aspects of HTTP ; dessiner le chemin navigateur → API → réponse.', 'Components of HTTP-based systems et Basic aspects of HTTP', 15),
          ],
          readingDescription: 'Consulter les sections indiquées puis annoter la carte de requête SourceLab avec le processus, le port, la méthode, le statut et le point de journalisation attendu.',
          exerciseTitle: 'Dessiner et instrumenter la requête d’import',
          exerciseDescription: 'Créer un diagramme de la requête POST d’import depuis l’interface jusqu’à la réponse. Ajouter un request ID, journaliser le début et la fin côté API, puis joindre une capture ou un extrait montrant le même identifiant dans la réponse et le log.',
          concept: {
            title: 'Chaîne d’exécution d’une requête',
            slug: 'chaine-execution-requete',
            description: 'Une requête traverse une suite de frontières observables — client, réseau, serveur, logique métier et dépendances — dont chacune possède un contrat, un état et des preuves distincts.',
            misconception: 'Le navigateur communique directement avec la base de données ; un écran bloqué indique donc une erreur SQL.',
            trueStatement: 'Un statut HTTP 500 prouve que le serveur a produit une réponse d’erreur, mais ne suffit pas à identifier la dépendance fautive.',
            falseStatement: 'Si curl répond correctement depuis le serveur, le parcours utilisateur complet est nécessairement sain.',
            trueExplanation: 'Le statut localise une frontière, pas la cause interne ni les autres chemins réseau.',
            falseExplanation: 'Le navigateur peut utiliser une autre origine, une autre configuration ou traverser d’autres intermédiaires.',
            scenarioPrompt: 'L’interface expire, alors que curl vers l’API locale répond 200. Quelle première décision est la plus rigoureuse ?',
            scenarioCorrect: 'Comparer l’URL, le réseau et la configuration réellement utilisés par le navigateur avant de modifier la base.',
            scenarioDistractors: ['Ajouter immédiatement un index PostgreSQL.', 'Augmenter tous les timeouts.', 'Réécrire la route Hono sans reproduire la requête du navigateur.'],
            requiredItems: ['identifier la frontière en échec', 'collecter statut, durée et request ID', 'tester de l’extérieur vers l’intérieur'],
            badItems: ['modifier plusieurs couches simultanément', 'conclure à partir d’un seul redémarrage'],
            shortPrompt: 'Cite trois frontières d’une requête SourceLab et une preuve observable pour chacune.',
            acceptedAnswers: ['client réseau serveur', 'navigateur HTTP API', 'statut logs requête'],
            decisionRule: 'Localiser d’abord la première frontière dont le contrat n’est plus respecté ; seulement ensuite chercher la cause à l’intérieur de cette frontière.',
          },
        },
        {
          title: 'Diagnostiquer configuration, ports et arrêt',
          slug: 'diagnostiquer-configuration-ports-arret',
          minutes: 100,
          summary: 'Rendre les différences d’environnement visibles et vérifier écoute réseau, variables, dépendances et arrêt propre.',
          objectives: ['Expliquer la portée de localhost dans plusieurs processus ou containers.', 'Séparer configuration du code et secrets.', 'Tester un arrêt propre sans perdre un traitement en cours.'],
          explanation: 'La configuration n’est pas une constante du code : elle décrit l’environnement dans lequel le même artefact s’exécute. Un service doit échouer clairement lorsqu’une variable obligatoire manque, écouter sur l’interface attendue et traiter les signaux d’arrêt. Dans un environnement multi-processus, localhost désigne le processus ou le container courant ; le nom d’une dépendance doit être résolu dans le réseau concerné.',
          example: 'L’API SourceLab fonctionne sur la machine hôte mais échoue dans un container avec ECONNREFUSED vers localhost:5432. PostgreSQL est sain dans un autre container. La correction n’est pas de redémarrer PostgreSQL : l’API doit utiliser le nom DNS du service Compose et attendre sa disponibilité vérifiée.',
          resources: [
            resource(sources.nodeEnv, 'node-environment-variables', 'Lire la syntaxe et l’accès aux variables afin de construire une validation explicite de la configuration SourceLab.', 'Traiter la configuration comme une entrée validée.', 'Lire les sections Process.env et .env files ; lister les variables obligatoires, optionnelles et secrètes du projet.', 'Process.env et .env files', 16),
            resource(sources.twelveDisposability, 'twelve-factor-disposability', 'Étudier démarrage rapide et arrêt gracieux afin de définir ce que doit faire le worker lors d’un SIGTERM.', 'Concevoir un service remplaçable sans corruption.', 'Lire la page puis écrire la séquence d’arrêt du worker : ne plus prendre de job, terminer ou rendre le verrou, fermer les connexions, quitter.', 'Page complète', 12),
          ],
          readingDescription: 'Construire une matrice local / test / staging avec ports, noms d’hôte, variables obligatoires et comportement attendu lorsqu’une valeur manque.',
          exerciseTitle: 'Créer un diagnostic de configuration au démarrage',
          exerciseDescription: 'Ajouter un schéma Zod de configuration à l’API et au worker. Provoquer une variable absente, un mauvais hostname et un SIGTERM ; capturer pour chaque cas le message, le code de sortie et l’absence de job laissé dans un état ambigu.',
          concept: {
            title: 'Configuration observable et arrêt gracieux',
            slug: 'configuration-observable-arret-gracieux',
            description: 'Un service fiable valide sa configuration au démarrage, expose clairement où il écoute et répond aux signaux en cessant proprement le travail avant de fermer ses dépendances.',
            misconception: 'Un fichier .env commité garantit que tous les environnements exécutent la même configuration.',
            trueStatement: 'Dans un container, localhost désigne ce container et non automatiquement un autre service Compose.',
            falseStatement: 'Un worker peut être tué à n’importe quel moment sans protocole si PostgreSQL est utilisé.',
            scenarioPrompt: 'L’API containerisée ne joint pas PostgreSQL avec localhost:5432 alors que la base est healthy. Que faut-il vérifier en premier ?',
            scenarioCorrect: 'Le nom DNS du service Compose, le réseau partagé et la variable DATABASE_URL au runtime.',
            scenarioDistractors: ['La couleur du réseau Docker.', 'Le bundle frontend.', 'Le nombre de questions des quiz LearnX.'],
            requiredItems: ['validation des variables obligatoires', 'adresse et port explicites', 'gestion de SIGTERM'],
            badItems: ['secrets dans l’image', 'valeurs de production codées en dur'],
            shortPrompt: 'Décris les quatre étapes d’un arrêt propre du worker SourceLab.',
            acceptedAnswers: ['cesser nouveaux jobs terminer fermer connexions quitter', 'stop acquire finish release close'],
            decisionRule: 'Une configuration invalide doit échouer tôt et explicitement ; un arrêt demandé doit préserver l’état du travail avant de rendre le processus remplaçable.',
          },
        },
      ],
    },
    {
      title: 'Containeriser un environnement reproductible',
      slug: 'containeriser-environnement',
      moduleTitle: 'Images et orchestration locale',
      moduleSlug: 'images-compose',
      days: 7,
      productOutcome: 'une commande unique qui démarre l’interface, l’API, le worker, PostgreSQL et le stockage local avec états de santé explicites.',
      assessment: stageAssessment(
        'Évaluation — Démarrer SourceLab avec Docker Compose',
        'Livrer un environnement reproductible démarré par une commande et vérifiable sans configuration cachée.',
        'Construire des images distinctes API et worker, lancer la stack avec Docker Compose, persister la base et les fichiers, ajouter des healthchecks et démontrer redémarrage, arrêt propre et absence de secret dans les images. Fournir un README de démarrage et une preuve des contrôles.',
        [
          { criterion: 'Images', weight: 25, requirements: ['Les builds sont multi-stage et reproductibles.', 'Le runtime n’embarque pas les dépendances ou fichiers inutiles.'] },
          { criterion: 'Orchestration', weight: 30, requirements: ['Les services communiquent par noms DNS internes.', 'Readiness et ordre de démarrage sont traités explicitement.'] },
          { criterion: 'Données et sécurité', weight: 25, requirements: ['Les données utiles survivent au redémarrage.', 'Aucun secret ni fichier local sensible n’est présent dans l’image.'] },
          { criterion: 'Expérience développeur', weight: 20, requirements: ['Une commande démarre la stack.', 'Le README permet à un tiers de vérifier les fonctionnalités.'] },
        ],
      ),
      lessons: [
        {
          title: 'Construire des images minimales et prévisibles',
          slug: 'construire-images-minimales',
          minutes: 110,
          summary: 'Comprendre image, container et couches pour produire des runtimes SourceLab petits, non-root et reproductibles.',
          objectives: ['Distinguer image, container et volume.', 'Écrire un Dockerfile multi-stage.', 'Expliquer l’impact du contexte et du cache de build.'],
          explanation: 'Une image décrit un système de fichiers et une commande de démarrage immuables ; un container est une exécution isolée de cette image. Le build multi-stage sépare installation, compilation et runtime pour ne copier que l’artefact nécessaire. L’ordre des instructions influence le cache : les dépendances stables doivent être copiées avant le code changeant. Un .dockerignore réduit le contexte et évite d’envoyer secrets, caches ou sorties locales au daemon.',
          example: 'Le premier Dockerfile SourceLab copie tout le dépôt avant pnpm install et exécute l’API en root avec les devDependencies. Chaque modification invalide l’installation et l’image dépasse largement le besoin runtime. Le correctif sépare manifests, dépendances, build et image finale, puis copie uniquement dist et les modules de production.',
          resources: [
            resource(sources.dockerMultiStage, 'docker-multi-stage', 'Lire les mécanismes de stages nommés et de copie entre stages avant de construire les images API et worker.', 'Séparer build et runtime.', 'Lire la page complète puis dessiner les stages dependencies, build et runtime de SourceLab.', 'Page complète', 18),
            resource(sources.dockerBestPractices, 'docker-build-best-practices', 'Sélectionner les recommandations applicables : base de confiance, cache, .dockerignore, utilisateur et reconstruction régulière.', 'Réduire taille, surface et variance des images.', 'Lire les sections Use multi-stage builds, Choose the right base image, Exclude with .dockerignore et Build and test your images in CI.', 'Sections ciblées de la page', 20),
          ],
          readingDescription: 'Annoter un Dockerfile initial avec les couches, les invalidations de cache, les fichiers superflus et les privilèges du processus.',
          exerciseTitle: 'Containeriser l’API et le worker',
          exerciseDescription: 'Écrire deux cibles runtime partageant les stages communs. Mesurer taille et durée d’un build à froid puis après modification d’un fichier source ; vérifier utilisateur non-root, contenu de l’image et commande d’arrêt.',
          concept: {
            title: 'Image runtime reproductible',
            slug: 'image-runtime-reproductible',
            description: 'Une image runtime reproductible est construite depuis des entrées versionnées, sépare compilation et exécution, contient uniquement les artefacts nécessaires et démarre avec des privilèges minimaux.',
            misconception: 'Un container est une petite machine virtuelle dont l’état interne doit être conservé entre deux déploiements.',
            trueStatement: 'Copier les manifests de dépendances avant le code permet au cache de réutiliser l’installation lorsque les dépendances ne changent pas.',
            falseStatement: 'Plus une image contient d’outils de debug et de devDependencies, plus elle est fiable en production.',
            scenarioPrompt: 'Une modification README relance pnpm install dans chaque build. Quel changement est le plus pertinent ?',
            scenarioCorrect: 'Réordonner les COPY pour installer depuis les manifests avant de copier le reste du contexte.',
            scenarioDistractors: ['Désactiver entièrement le cache.', 'Ajouter un volume à l’image.', 'Exécuter le container en mode privilégié.'],
            requiredItems: ['stages build et runtime séparés', '.dockerignore', 'utilisateur non-root'],
            badItems: ['secrets copiés dans l’image', 'node_modules local envoyé au build'],
            shortPrompt: 'Explique en une phrase la différence entre une image, un container et un volume.',
            acceptedAnswers: ['image modèle container exécution volume données persistantes', 'artefact exécution stockage persistant'],
            decisionRule: 'L’image finale doit être suffisante pour exécuter le service, mais insuffisante pour transporter le poste de développement ou un secret.',
          },
        },
        {
          title: 'Orchestrer web, API, worker, base et fichiers',
          slug: 'orchestrer-services-compose',
          minutes: 115,
          summary: 'Utiliser Compose pour rendre les dépendances, réseaux, volumes et critères de disponibilité explicites.',
          objectives: ['Configurer la découverte de services par DNS Compose.', 'Distinguer démarrage et readiness.', 'Choisir entre bind mount et volume nommé.'],
          explanation: 'Compose décrit un environnement multi-services, pas seulement une liste de containers. Les services d’un réseau partagé se découvrent par leur nom ; les ports publiés concernent l’accès depuis l’hôte, pas la communication interne. depends_on ordonne la création, mais une dépendance n’est utilisable que lorsque son test de santé ou son protocole de reprise le confirme. Les volumes nommés conviennent aux données gérées par le runtime ; les bind mounts servent surtout à exposer des fichiers du poste pendant le développement.',
          example: 'Le worker SourceLab démarre avant PostgreSQL, échoue une fois et quitte. Ajouter seulement depends_on déplace parfois la course sans la supprimer. La stack combine un healthcheck PostgreSQL, une condition service_healthy et un retry borné du worker, puis expose un statut distinct pour les jobs en attente.',
          resources: [
            resource(sources.composeStartup, 'compose-startup-order', 'Étudier service_started, service_healthy et service_completed_successfully pour définir les dépendances de SourceLab.', 'Distinguer ordre de création et disponibilité.', 'Lire la page puis écrire les conditions de démarrage de l’API et du worker.', 'Page complète', 16),
            resource(sources.composeNetworking, 'compose-networking', 'Comprendre noms de services, ports de container et ports publiés afin de corriger les URLs internes.', 'Faire communiquer les services sans dépendre de localhost.', 'Lire Update containers on the network et Link containers ; produire la table hôte/port interne/externe.', 'Sections ciblées', 15),
          ],
          readingDescription: 'Produire une table de chaque service avec hostname interne, port interne, port publié, données persistantes et healthcheck.',
          exerciseTitle: 'Écrire compose.yaml et vérifier les cycles de vie',
          exerciseDescription: 'Orchestrer web, API, worker, PostgreSQL et un stockage compatible S3 local ou dossier dédié. Démontrer démarrage depuis zéro, persistance après restart, résolution DNS interne, état unhealthy volontaire et récupération contrôlée.',
          concept: {
            title: 'Readiness d’un système multi-services',
            slug: 'readiness-systeme-multi-services',
            description: 'La readiness exprime qu’un service peut traiter correctement une requête dépendante, ce qui est plus exigeant que le simple fait que son processus soit démarré.',
            misconception: 'depends_on garantit que la base a terminé son initialisation et répond à toutes les requêtes.',
            trueStatement: 'Un port publié permet l’accès depuis l’hôte ; les services Compose utilisent normalement le port interne et le nom du service.',
            falseStatement: 'Le statut running d’un container suffit à prouver que l’application est prête.',
            scenarioPrompt: 'Le worker démarre avant que PostgreSQL accepte les connexions. Quelle combinaison est la plus robuste ?',
            scenarioCorrect: 'Healthcheck de la base, condition service_healthy et retry borné côté worker.',
            scenarioDistractors: ['Un sleep fixe de 30 secondes.', 'Publier tous les ports de PostgreSQL sur Internet.', 'Relancer Compose jusqu’à ce que cela fonctionne.'],
            requiredItems: ['healthcheck pertinent', 'DNS de service', 'persistance explicitement choisie'],
            badItems: ['localhost entre containers', 'sleep arbitraire comme unique contrôle'],
            shortPrompt: 'Pourquoi running et ready ne sont-ils pas synonymes ?',
            acceptedAnswers: ['processus démarré dépendances pas prêtes', 'running vivant ready capable servir'],
            decisionRule: 'Un service ne doit annoncer sa disponibilité que lorsque ses dépendances et invariants nécessaires à la requête sont vérifiés.',
          },
        },
      ],
    },
    {
      title: 'Intégrer API, fichiers et traitements asynchrones',
      slug: 'integrer-api-worker',
      moduleTitle: 'Contrats et jobs',
      moduleSlug: 'contrats-jobs',
      days: 7,
      productOutcome: 'une verticale « importer une source » qui crée un job, traite un fichier et expose un résultat sans doublon.',
      assessment: stageAssessment(
        'Évaluation — Livrer la verticale d’import',
        'Transformer un fichier envoyé par l’utilisateur en source traitée par un worker, avec états et erreurs explicites.',
        'Implémenter le contrat d’import, le stockage du fichier, la création atomique d’un job, la prise en charge par le worker et la consultation du statut. Rejouer la même requête, interrompre le worker et simuler une dépendance indisponible. Prouver qu’aucun résultat n’est dupliqué et que les erreurs définitives sont distinguées des erreurs récupérables.',
        [
          { criterion: 'Contrat produit', weight: 25, requirements: ['Les statuts et erreurs sont compréhensibles par le client.', 'Validation, taille et type de fichier sont contrôlés.'] },
          { criterion: 'Idempotence', weight: 30, requirements: ['Une répétition du même intent ne duplique pas la source.', 'La clé et le résultat idempotents sont persistés atomiquement.'] },
          { criterion: 'Worker et reprise', weight: 30, requirements: ['La concurrence ne permet pas deux propriétaires du même job.', 'Retries bornés et erreurs définitives sont observables.'] },
          { criterion: 'Preuves', weight: 15, requirements: ['Les scénarios sont couverts par des tests.', 'Le journal des états permet de comprendre chaque transition.'] },
        ],
      ),
      lessons: [
        {
          title: 'Concevoir le contrat d’import d’une source',
          slug: 'concevoir-contrat-import-source',
          minutes: 105,
          summary: 'Définir l’expérience API visible par l’utilisateur avant de relier stockage, job et worker.',
          objectives: ['Choisir les statuts HTTP selon le résultat observable.', 'Valider données et fichier à la frontière.', 'Versionner un contrat sans exposer le modèle Prisma.'],
          explanation: 'Le contrat d’import décrit un intent produit : créer ou retrouver une source à partir d’un matériau. Il distingue validation synchrone et traitement asynchrone. Une réponse 202 peut retourner un identifiant de job et une URL de statut ; un conflit idempotent peut renvoyer la ressource existante plutôt qu’une erreur vague. Les erreurs utilisent une forme stable avec code, message sûr, request ID et détails validés. Le modèle externe ne doit pas être une sérialisation accidentelle de la table interne.',
          example: 'SourceLab reçoit un PDF trop volumineux. L’API ne doit ni créer un job impossible ni répondre 500. Elle valide taille et type, renvoie 413 avec un code métier stable et conserve le request ID. Pour un fichier accepté, elle répond 202 avec sourceId, jobId, status et lien de consultation.',
          resources: [
            resource(sources.honoValidation, 'hono-validation-guide', 'Lire le fonctionnement du middleware validator et les limites liées aux headers avant de concevoir les schémas d’entrée.', 'Valider la requête à la frontière Hono.', 'Lire la page complète puis écrire les schémas Zod du formulaire, des métadonnées et de la réponse.', 'Page complète', 16),
            resource(sources.mdnStatus, 'mdn-http-status', 'Revoir les familles de statuts et sélectionner ceux correspondant aux issues de l’import.', 'Associer une issue produit à un statut HTTP.', 'Lire les entrées 201, 202, 400, 409, 413, 415, 422 et 500 ; justifier la réponse de huit scénarios.', 'Statuts ciblés', 18),
          ],
          readingDescription: 'Construire une table scénario → statut HTTP → code d’erreur métier → action possible pour l’utilisateur.',
          exerciseTitle: 'Spécifier et implémenter POST /sources/imports',
          exerciseDescription: 'Écrire le contrat Zod d’entrée et de sortie, normaliser les erreurs et implémenter la route Hono avec limites de taille/type. Ajouter des tests de contrat pour succès accepté, validation, média non supporté, payload trop grand et répétition idempotente.',
          concept: {
            title: 'Contrat d’API orienté résultat',
            slug: 'contrat-api-oriente-resultat',
            description: 'Un contrat d’API stable expose l’intention, les états et les erreurs utiles au client sans révéler les détails accidentels de stockage ou d’implémentation.',
            misconception: 'Une API interne peut renvoyer directement les objets Prisma, puisque le frontend appartient au même projet.',
            trueStatement: 'Une réponse 202 Accepted convient lorsque la requête est acceptée mais que le traitement n’est pas encore terminé.',
            falseStatement: 'Toute erreur de fichier doit être renvoyée en 500 afin d’être visible dans les logs.',
            scenarioPrompt: 'Un PDF dépasse la limite annoncée avant création du job. Quelle réponse est la plus cohérente ?',
            scenarioCorrect: '413 avec un code métier stable, la limite et le request ID.',
            scenarioDistractors: ['202 puis échec silencieux du worker.', '500 avec la stack.', '200 avec status unknown.'],
            requiredItems: ['validation à la frontière', 'forme d’erreur stable', 'états asynchrones explicites'],
            badItems: ['stack serveur exposée', 'objet ORM utilisé comme contrat public'],
            shortPrompt: 'Que doit contenir au minimum la réponse 202 de l’import SourceLab ?',
            acceptedAnswers: ['jobId sourceId status lien', 'identifiant job statut URL'],
            decisionRule: 'Le client doit pouvoir comprendre ce qui a été accepté, ce qui reste à faire et quelle action entreprendre sans connaître la structure interne du service.',
          },
        },
        {
          title: 'Exécuter des jobs idempotents avec un worker',
          slug: 'executer-jobs-idempotents-worker',
          minutes: 125,
          summary: 'Séparer réponse HTTP et traitement long tout en rendant retries, concurrence et reprise sûrs.',
          objectives: ['Définir les transitions d’état d’un job.', 'Garantir l’idempotence de l’intent.', 'Distinguer erreur récupérable, définitive et job bloqué.'],
          explanation: 'Un système de jobs accepte que le même message ou intent soit observé plusieurs fois. L’idempotence associe une identité stable à l’opération et persiste le résultat avec les effets métier dans une transaction. Le worker acquiert un job éligible, marque un lease ou un propriétaire, traite, puis confirme succès ou échec. Les retries sont bornés, espacés et réservés aux erreurs temporaires. Une opération inconnue ou un fichier invalide ne devient pas correcte après dix tentatives.',
          example: 'L’utilisateur double-clique sur Importer pendant qu’un timeout masque la première réponse. Les deux requêtes portent la même clé construite depuis le projet et le hash du fichier. La transaction retourne le même sourceId et le même job. Après arrêt brutal du worker, le lease expire et un autre worker reprend sans créer une deuxième version du document.',
          resources: [
            resource(sources.awsIdempotency, 'aws-idempotent-apis', 'Lire les sections sur caller-provided request identifiers, retries et late-arriving requests pour cadrer la clé SourceLab.', 'Rendre les retries sûrs au niveau de l’intent.', 'Lire le document puis comparer clé dérivée du payload et clé fournie par le client.', 'Same client request ID, different intent et Late arriving requests', 24),
            resource(sources.postgresTransactions, 'postgres-transactions-jobs', 'Revoir atomicité et rollback avant de regrouper source, clé idempotente et job dans une transaction.', 'Garantir un état métier atomique.', 'Lire la page puis écrire l’invariant qui doit être vrai après commit ou rollback.', 'Page complète', 14),
          ],
          readingDescription: 'Dessiner la machine d’états PENDING, PROCESSING, SUCCEEDED, RETRYABLE_FAILED et FAILED avec transitions, propriétaire, tentative suivante et terminalité.',
          exerciseTitle: 'Implémenter le worker interrompable',
          exerciseDescription: 'Créer la table de jobs, l’acquisition concurrente et la boucle du worker. Tester double requête, deux workers, erreur temporaire, erreur définitive et arrêt après acquisition. Prouver par requêtes SQL qu’une source ne possède qu’un résultat canonique.',
          concept: {
            title: 'Idempotence d’un traitement asynchrone',
            slug: 'idempotence-traitement-asynchrone',
            description: 'Un traitement idempotent peut recevoir plusieurs fois le même intent sans multiplier ses effets métier, grâce à une identité stable et une persistance atomique du résultat.',
            misconception: 'L’idempotence consiste à ignorer toute deuxième requête ayant exactement le même JSON.',
            trueStatement: 'Une clé idempotente doit distinguer la répétition du même intent d’une nouvelle opération légitime.',
            falseStatement: 'Un retry illimité est sûr dès lors que la fonction du worker est idempotente.',
            scenarioPrompt: 'Deux workers lisent le même job PENDING. Quel mécanisme empêche un double traitement ?',
            scenarioCorrect: 'Une acquisition atomique ou un verrou avec propriétaire et lease vérifié.',
            scenarioDistractors: ['Une variable globale dans chaque processus.', 'Un délai aléatoire sans mise à jour en base.', 'Le nom différent des containers.'],
            requiredItems: ['clé liée à l’intent', 'transaction des effets', 'retries bornés et classifiés'],
            badItems: ['retry de toute erreur', 'état uniquement en mémoire'],
            shortPrompt: 'Donne un exemple de même requête répétée et un exemple de nouvel intent qui ne doit pas partager sa clé.',
            acceptedAnswers: ['double clic même fichier nouveau fichier nouvelle clé', 'timeout retry même intent modification nouveau intent'],
            decisionRule: 'Avant d’ajouter un retry, définir l’identité de l’intent, l’effet unique attendu et la preuve durable qu’il a déjà été appliqué.',
          },
        },
      ],
    },
    {
      title: 'Persister et faire évoluer les données',
      slug: 'faire-evoluer-donnees',
      moduleTitle: 'Modèle, migrations et performance',
      moduleSlug: 'modele-migrations-performance',
      days: 7,
      productOutcome: 'un modèle de sources et versions cohérent, migré sans perte et mesuré sur les requêtes réelles de SourceLab.',
      assessment: stageAssessment(
        'Évaluation — Faire évoluer le modèle SourceLab',
        'Ajouter versionnement et détection de doublons sans casser les données de démonstration ni l’ancienne API.',
        'Créer une migration additive, backfiller hash et version, maintenir une phase de compatibilité, mesurer la requête de liste et justifier tout index ajouté. Exécuter migration et seed deux fois sur une base isolée, comparer les décomptes et documenter roll-forward et restauration.',
        [
          { criterion: 'Modèle et invariants', weight: 25, requirements: ['Les contraintes expriment les invariants métier.', 'Source, fichier, version et job ne sont pas confondus.'] },
          { criterion: 'Migration sûre', weight: 30, requirements: ['Ajout, backfill, bascule et suppression sont séparés.', 'Le déploiement reste compatible pendant la transition.'] },
          { criterion: 'Mesure', weight: 25, requirements: ['EXPLAIN est collecté avant et après.', 'L’index est justifié par une requête et un volume.'] },
          { criterion: 'Reprise', weight: 20, requirements: ['Le plan de roll-forward est priorisé.', 'Les conséquences d’une restauration sont explicites.'] },
        ],
      ),
      lessons: [
        {
          title: 'Modéliser sources, fichiers, versions et états',
          slug: 'modeliser-sources-fichiers-versions',
          minutes: 115,
          summary: 'Traduire la promesse produit SourceLab en entités, contraintes et transactions plutôt qu’en table unique surchargée.',
          objectives: ['Distinguer identité métier et occurrence technique.', 'Exprimer les invariants avec contraintes.', 'Choisir la frontière transactionnelle d’un import.'],
          explanation: 'Une Source représente l’objet éditorial que l’utilisateur classe et annote. Un SourceFile représente un blob stocké et son hash. Une SourceVersion conserve le texte extrait, les métadonnées et la provenance d’un traitement donné. Le Job décrit l’exécution. Les contraintes uniques, clés étrangères et checks empêchent des états impossibles. La transaction regroupe les écritures qui doivent apparaître ensemble, sans englober un appel externe long.',
          example: 'Deux projets peuvent référencer le même fichier physique sans partager leurs décisions éditoriales. SourceLab peut dédupliquer le blob par hash tout en créant deux Sources rattachées à des projets différents. Supprimer une Source ne doit pas effacer un blob encore référencé ; une politique séparée décide quand le stockage devient orphelin.',
          resources: [
            resource(sources.postgresConstraints, 'postgres-constraints-sources', 'Lire NOT NULL, unique, primary key, foreign key et check pour traduire les invariants SourceLab.', 'Faire protéger les invariants par PostgreSQL.', 'Lire les sections 5.5.1 à 5.5.5 puis associer chaque invariant du modèle à une contrainte ou à une transaction.', 'Sections Not-Null, Unique, Primary Keys, Foreign Keys et Check Constraints', 22),
            resource(sources.prismaTransactions, 'prisma-transactions-sources', 'Comparer nested writes, transactions séquentielles et interactive transactions avant de définir la frontière d’import.', 'Choisir une transaction proportionnée.', 'Lire les sections Transactions overview, Nested writes et Idempotent APIs ; écrire ce qui doit être atomique et ce qui reste hors transaction.', 'Transactions overview, Nested writes et Idempotent APIs', 20),
          ],
          readingDescription: 'Produire un dictionnaire Source, SourceFile, SourceVersion, ProcessingJob et ProjectSource avec identité, propriétaire, cycle de vie et contraintes.',
          exerciseTitle: 'Créer le modèle Prisma et ses invariants',
          exerciseDescription: 'Implémenter le schéma, générer une migration et écrire des tests qui tentent doublon interdit, référence invalide, transition impossible et partage valide d’un blob entre deux projets.',
          concept: {
            title: 'Invariant persistant',
            slug: 'invariant-persistant',
            description: 'Un invariant persistant est une condition métier qui doit rester vraie malgré concurrence, erreur ou redémarrage et qui est protégée au plus près de la transaction et de la base.',
            misconception: 'Les contrôles Zod du frontend suffisent à empêcher les données impossibles dans PostgreSQL.',
            trueStatement: 'Une contrainte unique protège aussi contre deux requêtes concurrentes que le code applicatif a validées séparément.',
            falseStatement: 'Une transaction doit inclure l’upload vers un fournisseur externe afin que tout soit atomique.',
            scenarioPrompt: 'Deux requêtes concurrentes créent la même version de hash. Où protéger l’unicité ?',
            scenarioCorrect: 'Avec une contrainte unique adaptée et une gestion explicite du conflit dans la transaction.',
            scenarioDistractors: ['Dans un state React.', 'Avec un délai avant INSERT.', 'Dans un commentaire de code.'],
            requiredItems: ['contrainte en base', 'frontière transactionnelle', 'cycle de vie explicite'],
            badItems: ['validation uniquement côté client', 'cascade de suppression non examinée'],
            shortPrompt: 'Distingue Source, SourceFile et SourceVersion dans SourceLab.',
            acceptedAnswers: ['source objet éditorial fichier blob version extraction métadonnées', 'source classification file stockage version traitement'],
            decisionRule: 'Tout état dont la violation créerait une incohérence durable doit être protégé par la base ou la transaction, pas seulement par le chemin heureux du code.',
          },
        },
        {
          title: 'Migrer, indexer et mesurer sans casser',
          slug: 'migrer-indexer-mesurer',
          minutes: 125,
          summary: 'Faire évoluer le schéma en plusieurs phases et décider d’un index à partir d’une requête mesurée.',
          objectives: ['Séparer migration additive, backfill et retrait.', 'Lire un plan EXPLAIN.', 'Évaluer le coût d’un index sur lectures et écritures.'],
          explanation: 'Une migration sûre accepte une période où ancienne et nouvelle versions du code coexistent. On ajoute d’abord un champ nullable ou une table, déploie un code capable de lire les deux formes, backfille par lots, active la nouvelle écriture, vérifie, puis seulement rend la contrainte stricte ou retire l’ancien chemin. Un index accélère certaines recherches en échange de stockage et de travail à chaque écriture ; il est justifié par la requête, l’ordre, les filtres et la distribution réelle.',
          example: 'SourceLab ajoute normalizedTitle pour la détection de doublons. Rendre immédiatement la colonne NOT NULL échoue sur les lignes existantes. Le plan ajoute la colonne, calcule les valeurs par lot, fait écrire les deux champs, mesure la requête projet + normalizedTitle, puis ajoute la contrainte après contrôle des nulls.',
          resources: [
            resource(sources.prismaMigrate, 'prisma-migrate-production', 'Lire la séparation migrate dev / migrate deploy et les précautions de production avant d’écrire le plan SourceLab.', 'Déployer uniquement des migrations versionnées.', 'Lire Development environments et Production and testing environments ; comparer les commandes autorisées.', 'Development environments et Production and testing environments', 18),
            resource(sources.postgresExplain, 'postgres-explain-sourcelab', 'Lire coûts, nœuds et EXPLAIN ANALYZE afin de comparer la requête de liste avant et après index.', 'Mesurer un plan sans confondre estimation et durée réelle.', 'Lire la section Using EXPLAIN puis capturer plan, lignes estimées/réelles et buffers si disponibles pour la requête ciblée.', 'Introduction et EXPLAIN ANALYZE', 22),
          ],
          readingDescription: 'Écrire une migration en quatre phases et un protocole de mesure avant toute création d’index.',
          exerciseTitle: 'Migrer le versionnement et justifier un index',
          exerciseDescription: 'Ajouter normalizedTitle et currentVersionId avec backfill borné. Générer un jeu de données, mesurer la liste filtrée d’un projet, proposer ou refuser un index composé et documenter résultat, coût d’écriture et stratégie de retrait.',
          concept: {
            title: 'Évolution compatible du schéma',
            slug: 'evolution-compatible-schema',
            description: 'Une évolution compatible découple ajout, migration des données, bascule du code et retrait afin que chaque étape soit observable, réversible ou corrigeable sans interrompre l’ancien contrat.',
            misconception: 'Une migration qui passe sur une base vide est suffisamment sûre pour la production.',
            trueStatement: 'EXPLAIN décrit le plan choisi ; EXPLAIN ANALYZE exécute la requête et doit être utilisé prudemment sur une mutation.',
            falseStatement: 'Ajouter un index ne peut qu’améliorer les performances et n’a pas de coût sur les écritures.',
            scenarioPrompt: 'Une nouvelle colonne doit devenir NOT NULL sur 100 000 lignes existantes. Quel ordre est le plus prudent ?',
            scenarioCorrect: 'Ajouter nullable, déployer compatibilité, backfiller par lots, vérifier, puis ajouter la contrainte.',
            scenarioDistractors: ['Ajouter NOT NULL sans valeur.', 'Supprimer puis recréer la table.', 'Créer trois index avant de mesurer.'],
            requiredItems: ['compatibilité temporaire', 'backfill borné', 'mesure avant et après'],
            badItems: ['migration improvisée en production', 'index spéculatif sans requête cible'],
            shortPrompt: 'Quelles preuves réunir avant de conserver un nouvel index ?',
            acceptedAnswers: ['requête cible plan avant après volume coût écriture', 'explain analyse gain stockage write cost'],
            decisionRule: 'Ne rendre irréversible qu’une étape dont les données, le code et les mesures ont déjà confirmé la nouvelle forme.',
          },
        },
      ],
    },
    {
      title: 'Prouver l’intégration et automatiser la livraison',
      slug: 'tester-et-livrer',
      moduleTitle: 'Tests réels et CI/CD',
      moduleSlug: 'tests-ci-cd',
      days: 7,
      productOutcome: 'une CI qui recrée l’environnement, vérifie la verticale d’import, conserve ses preuves et déploie un staging identifiable.',
      assessment: stageAssessment(
        'Évaluation — Construire la chaîne de preuve SourceLab',
        'Automatiser la vérification du même artefact de la pull request au staging.',
        'Créer un workflow qui contrôle formatage et types, construit les images, démarre une base isolée, applique les migrations, exécute tests unitaires et intégration, conserve rapports, publie un artefact identifié par le commit, déploie en staging et lance un smoke test. Expliquer ce qui est mocké, ce qui est réel et pourquoi.',
        [
          { criterion: 'Stratégie de test', weight: 25, requirements: ['Chaque risque est couvert au niveau le moins coûteux qui reste probant.', 'La base et le worker réels sont utilisés pour la verticale critique.'] },
          { criterion: 'Reproductibilité CI', weight: 30, requirements: ['L’environnement est isolé et nettoyé même après échec.', 'Les versions et caches ne rendent pas le résultat ambigu.'] },
          { criterion: 'Promotion', weight: 25, requirements: ['L’artefact est identifié par le commit.', 'Le staging et son smoke test précèdent toute promotion.'] },
          { criterion: 'Diagnostic', weight: 20, requirements: ['Rapports et logs sont conservés comme artefacts.', 'Un échec permet d’identifier la couche fautive.'] },
        ],
      ),
      lessons: [
        {
          title: 'Tester une verticale avec de vraies dépendances',
          slug: 'tester-verticale-dependances-reelles',
          minutes: 120,
          summary: 'Choisir entre unité, intégration, contrat, E2E et smoke selon la preuve recherchée.',
          objectives: ['Associer un risque au bon niveau de test.', 'Isoler une base réelle par exécution.', 'Tester interruption, retry et concurrence sans faux succès.'],
          explanation: 'Un test unitaire prouve rapidement une règle pure ; il ne prouve pas que Prisma, PostgreSQL, le worker et le stockage s’accordent. Le test d’intégration démarre les vraies dépendances critiques et contrôle le contrat de la verticale. L’E2E ajoute l’interface lorsque le risque dépend réellement du navigateur. Un smoke test post-déploiement vérifie un petit nombre de capacités vitales sur l’artefact déployé. Les fixtures sont minimales, déterministes et rattachées à l’exécution.',
          example: 'Mocker le repository de jobs rend le test du retry vert même si la requête SQL permet à deux workers d’acquérir la même ligne. SourceLab garde des tests unitaires pour la politique de retry, puis un test PostgreSQL réel démarre deux workers et affirme qu’un seul résultat est créé.',
          resources: [
            resource(sources.testcontainers, 'testcontainers-node-quickstart', 'Suivre le cycle démarrage, port mappé, attente et arrêt d’un container de test avant de créer une base isolée.', 'Exécuter les tests contre une dépendance jetable.', 'Lire le quickstart et adapter l’exemple à PostgreSQL avec une identité d’exécution unique.', 'Page complète', 18),
            resource(sources.playwrightApi, 'playwright-api-testing', 'Lire les usages d’APIRequestContext pour tester directement l’API et préparer l’état d’un parcours navigateur.', 'Tester le contrat HTTP sans passer systématiquement par l’UI.', 'Lire Writing API Test et Reusing authentication state ; écrire un smoke import → statut.', 'Writing API Test et Reusing authentication state', 18),
          ],
          readingDescription: 'Créer une matrice risque → niveau de test → dépendances réelles → données → durée acceptable.',
          exerciseTitle: 'Écrire le test d’intégration de l’import',
          exerciseDescription: 'Démarrer PostgreSQL isolé, appliquer les migrations, lancer API et worker, importer un fichier, attendre SUCCEEDED puis vérifier version et hash. Ajouter les scénarios double import, worker interrompu et erreur définitive ; supprimer l’environnement dans un finally.',
          concept: {
            title: 'Preuve d’intégration',
            slug: 'preuve-integration',
            description: 'Une preuve d’intégration vérifie que les contrats entre composants réels produisent l’état attendu, y compris sur les pannes que les doubles de test masqueraient.',
            misconception: 'Un grand test E2E remplace avantageusement tous les tests unitaires et d’intégration.',
            trueStatement: 'Une dépendance jetable par exécution réduit les interférences et rend l’échec plus reproductible.',
            falseStatement: 'Mocker PostgreSQL est suffisant pour valider un verrou concurrent entre deux workers.',
            scenarioPrompt: 'Quel test prouve le mieux qu’un seul worker acquiert un job ?',
            scenarioCorrect: 'Un test d’intégration avec PostgreSQL réel et deux workers concurrents.',
            scenarioDistractors: ['Un snapshot du composant React.', 'Un test de la fonction de couleur du statut.', 'Un lint du fichier SQL.'],
            requiredItems: ['dépendance réelle critique', 'isolation par exécution', 'nettoyage garanti'],
            badItems: ['données partagées entre runs', 'attentes fixes sans condition'],
            shortPrompt: 'Quand préférer un test d’intégration à un test unitaire dans SourceLab ?',
            acceptedAnswers: ['contrat entre composants base worker stockage', 'risque dépendance réelle concurrence SQL'],
            decisionRule: 'Utiliser la preuve la moins coûteuse qui traverse toutes les frontières responsables du risque étudié, et aucune frontière inutile.',
          },
        },
        {
          title: 'Construire une CI/CD avec artefacts et environnements',
          slug: 'construire-ci-cd-artefacts',
          minutes: 125,
          summary: 'Transformer les vérifications locales en chaîne reproductible puis promouvoir un artefact identifiable.',
          objectives: ['Structurer jobs, dépendances et permissions GitHub Actions.', 'Conserver les preuves utiles comme artefacts.', 'Séparer preview, staging et production.'],
          explanation: 'La CI reconstruit la preuve à partir du commit : installation figée, génération, tests, images et rapports. Les jobs séparent les responsabilités mais partagent des artefacts immuables plutôt que de reconstruire silencieusement une autre version. Les environnements protègent secrets et promotion. Le CD déploie l’artefact déjà vérifié, exécute un smoke test et conserve le lien commit → image → déploiement. Une étape de nettoyage utilise always afin de ne pas laisser une base ou un stockage de test après échec.',
          example: 'Le workflow SourceLab teste le commit A mais le staging reconstruit latest après le commit B. Le smoke vert ne prouve rien sur A. Le pipeline tague l’image avec le SHA, publie son digest, puis déploie exactement ce digest en staging avant approbation.',
          resources: [
            resource(sources.githubWorkflows, 'github-actions-workflows', 'Lire événements, jobs, steps et runners avant de dessiner le workflow SourceLab.', 'Décomposer une CI en preuves ordonnées.', 'Lire Components of a workflow et Triggering a workflow ; dessiner le graphe lint → build → integration → staging.', 'Components of a workflow et Triggering a workflow', 17),
            resource(sources.githubArtifacts, 'github-actions-artifacts', 'Étudier upload/download-artifact, rétention et digest afin de conserver rapports et transmettre l’image ou ses métadonnées.', 'Partager des sorties sans les reconstruire.', 'Lire la page puis définir artefacts, noms, rétention et consommateurs de SourceLab.', 'Page complète', 16),
          ],
          readingDescription: 'Dessiner le pipeline, ses permissions, secrets, caches, artefacts, conditions de nettoyage et gates de promotion.',
          exerciseTitle: 'Automatiser build, intégration et staging',
          exerciseDescription: 'Créer le workflow de pull request et un déploiement staging protégé. Publier rapports de tests et performance, identifier l’image par SHA/digest, exécuter un smoke import et démontrer qu’un échec d’intégration bloque la promotion.',
          concept: {
            title: 'Promotion d’un artefact vérifié',
            slug: 'promotion-artefact-verifie',
            description: 'La promotion déplace le même artefact immuable entre environnements en conservant le lien avec le commit et les preuves qui l’ont validé.',
            misconception: 'Rebuilder le code dans chaque environnement garantit une meilleure adaptation locale.',
            trueStatement: 'Un artefact identifié par digest permet de vérifier que staging et production exécutent les mêmes octets.',
            falseStatement: 'Un cache de dépendances peut être traité comme la preuve finale du build.',
            scenarioPrompt: 'Le staging reconstruit latest après les tests du SHA A. Quel risque principal apparaît ?',
            scenarioCorrect: 'Le déploiement peut contenir un autre code que l’artefact testé.',
            scenarioDistractors: ['Le nom du workflow est trop court.', 'PostgreSQL devient automatiquement multi-région.', 'Les quiz LearnX changent de langue.'],
            requiredItems: ['artefact lié au SHA', 'smoke post-déploiement', 'environnement et secrets séparés'],
            badItems: ['latest non traçable', 'production déployée avant les tests'],
            shortPrompt: 'Quelle différence fais-tu entre un cache et un artefact de livraison ?',
            acceptedAnswers: ['cache accélère artefact résultat versionné à promouvoir', 'cache optimisation artefact preuve immuable'],
            decisionRule: 'Construire une fois, identifier le résultat, vérifier ce résultat puis promouvoir exactement cette version.',
          },
        },
      ],
    },
    {
      title: 'Observer et restaurer le service',
      slug: 'observer-restaurer-service',
      moduleTitle: 'Observabilité et incidents',
      moduleSlug: 'observabilite-incidents',
      days: 7,
      productOutcome: 'une V1 SourceLab déployée, observable, accompagnée de seuils, d’un runbook et d’un postmortem issu d’un incident simulé.',
      assessment: stageAssessment(
        'Évaluation finale — Exploiter SourceLab V1',
        'Détecter, contenir et résoudre un incident sur la verticale d’import puis défendre la readiness de la V1.',
        'Déployer la V1 de démonstration, injecter une saturation de jobs ou une mauvaise configuration de base, détecter l’impact par métriques et logs, limiter les nouveaux imports, restaurer le service, vérifier les données puis rédiger chronologie, cause, facteurs contributifs et actions. Présenter la valeur produit, les SLI retenus et les limites avant la phase IA.',
        [
          { criterion: 'Détection et impact', weight: 20, requirements: ['Le symptôme utilisateur et les SLI dégradés sont identifiés.', 'Les logs et métriques évitent les données sensibles.'] },
          { criterion: 'Réponse', weight: 25, requirements: ['La contention précède les changements risqués.', 'La restauration est vérifiée sur service et données.'] },
          { criterion: 'Analyse', weight: 25, requirements: ['Cause et facteurs contributifs sont séparés.', 'Le postmortem reste factuel et sans blâme.'] },
          { criterion: 'Produit et prévention', weight: 30, requirements: ['La V1 apporte une boucle utilisateur complète.', 'Les actions sont priorisées, propriétaires et proportionnées.'] },
        ],
        'simulation',
      ),
      lessons: [
        {
          title: 'Instrumenter logs, métriques, traces et budgets',
          slug: 'instrumenter-observabilite-budgets',
          minutes: 120,
          summary: 'Observer SourceLab depuis l’expérience utilisateur jusqu’au job sans enregistrer les contenus ou secrets.',
          objectives: ['Distinguer logs, métriques et traces.', 'Définir SLI, seuils et budgets de latence.', 'Propager un identifiant de corrélation.'],
          explanation: 'Les logs décrivent des événements structurés, les métriques agrègent des séries mesurables et les traces relient les opérations d’une même requête. SourceLab doit suivre taux d’import accepté, temps jusqu’au traitement, profondeur de file, taux d’échec, retries et saturation de connexions. Le request ID devient correlation ID dans le job. Les noms de fichiers, extraits de documents, e-mails, cookies et secrets ne sont pas nécessaires au diagnostic et ne doivent pas être journalisés.',
          example: 'La médiane d’import reste à deux secondes, mais les 5 % les plus lents dépassent dix minutes parce que la file s’allonge. Une moyenne seule masque le problème. Le tableau montre p50/p95 du temps jusqu’à SUCCEEDED, queue depth, âge du plus vieux job et taux de retry par cause normalisée.',
          resources: [
            resource(sources.otelPrimer, 'otel-observability-primer', 'Lire la distinction logs, metrics et traces ainsi que le rôle du contexte distribué.', 'Choisir le signal adapté à chaque question opérationnelle.', 'Lire Reliability & Metrics, Traces et Logs ; associer cinq questions SourceLab à un signal.', 'Reliability & Metrics, Traces et Logs', 20),
            resource(sources.googleMonitoring, 'google-sre-monitoring', 'Étudier symptômes, causes, golden signals et simplicité avant de définir les SLI SourceLab.', 'Mesurer ce que l’utilisateur ressent et ce qui explique la dégradation.', 'Lire les sections Symptoms Versus Causes, The Four Golden Signals et Choosing an Appropriate Resolution.', 'Sections ciblées', 24),
          ],
          readingDescription: 'Créer un catalogue de signaux avec nom, type, unité, labels autorisés, seuil de revue, question répondue et données explicitement exclues.',
          exerciseTitle: 'Tracer l’import et construire le tableau minimal',
          exerciseDescription: 'Propager requestId/correlationId de l’API au job, produire des logs JSON normalisés et mesurer latence acceptation→succès, taux d’erreur et queue depth. Simuler dix imports lents et démontrer pourquoi p95 révèle le problème.',
          concept: {
            title: 'Signal orienté symptôme',
            slug: 'signal-oriente-symptome',
            description: 'Un signal orienté symptôme mesure directement la capacité vécue par l’utilisateur, tandis que les signaux de cause aident ensuite à expliquer sa dégradation.',
            misconception: 'Journaliser chaque payload complet garantit qu’aucune information de diagnostic ne sera perdue.',
            trueStatement: 'La profondeur de file et l’âge du plus vieux job peuvent expliquer une hausse du temps jusqu’au traitement.',
            falseStatement: 'Une moyenne de latence suffit à détecter tous les utilisateurs très lents.',
            scenarioPrompt: 'La moyenne reste stable mais certains imports prennent dix minutes. Quel indicateur ajouter ?',
            scenarioCorrect: 'Un percentile p95/p99 et l’âge du plus vieux job.',
            scenarioDistractors: ['Le nombre de lignes du README.', 'Le hash complet des mots de passe.', 'Le contenu intégral de chaque PDF.'],
            requiredItems: ['SLI utilisateur', 'labels à cardinalité bornée', 'corrélation requête-job'],
            badItems: ['contenu sensible dans les logs', 'alerte sur toute requête isolée sans seuil'],
            shortPrompt: 'Donne un log, une métrique et une trace utiles au même import SourceLab.',
            acceptedAnswers: ['log état job métrique latence trace api worker', 'événement transition taux durée span import'],
            decisionRule: 'Commencer par mesurer le symptôme utilisateur ; ajouter ensuite le minimum de contexte nécessaire pour remonter à la cause sans collecter le contenu métier.',
          },
        },
        {
          title: 'Répondre à un incident et choisir la restauration',
          slug: 'repondre-incident-restauration',
          minutes: 135,
          summary: 'Conduire détection, contention, restauration et apprentissage sans confondre vitesse et improvisation.',
          objectives: ['Prioriser impact et containment.', 'Choisir roll-forward, rollback ou restauration de données.', 'Rédiger un postmortem actionnable sans blâme.'],
          explanation: 'Pendant un incident, la première question est l’impact observable et sa progression. La contention peut désactiver les nouveaux imports, réduire la concurrence ou revenir à une configuration sûre. Le roll-forward corrige souvent mieux une migration additive ; le rollback applicatif n’est sûr que si le schéma et les écritures restent compatibles. Restaurer une base peut perdre des écritures postérieures et exige une décision explicite. Le postmortem reconstruit faits, décisions, facteurs contributifs et actions vérifiables.',
          example: 'Un déploiement augmente la concurrence du worker et épuise le pool PostgreSQL. SourceLab active un kill switch d’import, réduit les workers, laisse finir les jobs acquis et déploie un correctif de limite. Restaurer la base serait disproportionné : aucune donnée n’est corrompue. Le postmortem ajoute un test de charge borné et une alerte sur saturation du pool.',
          resources: [
            resource(sources.googlePostmortem, 'google-sre-postmortem', 'Lire les objectifs, critères et propriétés d’un postmortem sans blâme avant l’incident simulé.', 'Transformer un incident en actions vérifiables.', 'Lire Introduction, Postmortem Philosophy et Best Practices ; préparer le modèle chronologie, impact, cause, actions.', 'Introduction, Postmortem Philosophy et Best Practices', 24),
            resource(sources.owaspLogging, 'owasp-logging-cheat-sheet', 'Revoir événements à journaliser, données à exclure et vérification des logs afin de sécuriser les preuves d’incident.', 'Conserver des preuves utiles sans fuite.', 'Lire Which events to log, Data to exclude et Verification ; auditer cinq événements SourceLab.', 'Which events to log, Data to exclude et Verification', 20),
          ],
          readingDescription: 'Préparer un runbook d’import indisponible : impact, seuil d’arrêt, kill switch, commandes de vérification, propriétaires, communication et sortie d’incident.',
          exerciseTitle: 'Conduire l’incident et rédiger le postmortem',
          exerciseDescription: 'Injecter saturation ou variable erronée, annoncer l’impact, contenir, restaurer et vérifier service/données. Rédiger une chronologie avec preuves, distinguer déclencheur et causes systémiques, puis créer trois actions avec priorité, propriétaire et critère de clôture.',
          concept: {
            title: 'Restauration proportionnée',
            slug: 'restauration-proportionnee',
            description: 'Une restauration proportionnée réduit rapidement l’impact avec l’action la moins destructrice compatible avec l’état du code, du schéma et des données.',
            misconception: 'Le rollback du binaire précédent est toujours la réponse la plus rapide et la plus sûre.',
            trueStatement: 'Restaurer une sauvegarde peut supprimer des écritures réalisées après son point de création.',
            falseStatement: 'Le postmortem sert principalement à identifier la personne qui a introduit le défaut.',
            scenarioPrompt: 'Le pool est saturé mais aucune donnée n’est corrompue. Quelle première stratégie est proportionnée ?',
            scenarioCorrect: 'Contenir les nouveaux imports, réduire la concurrence et corriger la limite avant d’envisager une restauration de données.',
            scenarioDistractors: ['Restaurer immédiatement une sauvegarde ancienne.', 'Supprimer les jobs en cours sans inventaire.', 'Masquer les alertes jusqu’au lendemain.'],
            requiredItems: ['impact et chronologie', 'containment réversible', 'vérification service et données'],
            badItems: ['action destructive sans sauvegarde', 'recherche d’un coupable'],
            shortPrompt: 'Quand un roll-forward est-il préférable à un rollback ?',
            acceptedAnswers: ['migration incompatible correctif additif données préservées', 'ancien code incompatible schéma correction plus sûre'],
            decisionRule: 'Contenir d’abord, préserver les données, puis choisir la stratégie dont les hypothèses de compatibilité sont explicitement vérifiées.',
          },
        },
      ],
    },
  ],
};
